export interface Capability {
  slug: string;
  name: string;
  tagline: string;
  summary: string;
  problems: string[];
  included: string[];
  proofs: string[];
  kpis: { label: string; value: string }[];
  now: string;
  future: string;
  tags: string[];
  tools?: string[];
}

export const capabilities: Capability[] = [
  {
    slug: "operare-autonoma",
    name: "Operare autonomă & helpdesk",
    tagline: "Problemele cunoscute se rezolvă singure. Oamenii răspund în minute la ce e nou.",
    summary: "Suportul zilnic reinventat: intenții în loc de tichete, remedieri automate consemnate, oameni disponibili pentru judecată, nu pentru repetiție. Fiecare solicitare are responsabil, termen și explicație.",
    problems: ["Solicitările se pierd pe WhatsApp și nimeni nu știe ce e închis.", "Aceleași 20 de probleme se rezolvă manual, de sute de ori.", "Onboarding-ul unui om nou durează zile."],
    included: ["Portal cu intenții (angajare, plecare, echipament, acces) și tichete pentru restul", "Remediere automată pentru problemele cunoscute, cu jurnal explicat", "Suport uman la distanță și la sediu, cu timp de răspuns garantat", "Bază de cunoștințe a firmei tale, scrisă pe măsură ce lucrăm", "Instalări standard din imagine, în sub o oră"],
    proofs: ["Timp de răspuns și rezolvare per solicitare, vizibil live", "Ore umane consumate luna aceasta vs. luna trecută", "Lista remedierilor automate, cu motivul fiecăreia"],
    kpis: [{ label: "răspuns median", value: "11 min" }, { label: "rezolvate automat", value: "68%" }, { label: "ore umane / lună", value: "3,2" }],
    now: "Automatizăm nivelul 1 complet: parole, imprimante, servicii oprite, spațiu, certificate, conturi.",
    future: "În 2126 nu mai există helpdesk. Există intenții și un sistem care le împlinește și le explică.",
    tags: ["intenții", "SLA", "on-site & remote"],
  },
  {
    slug: "identitate",
    name: "Identitate, Microsoft 365 & Google Workspace",
    tagline: "Cine are acces la ce, verificat zilnic. Conturi curate la plecare, în prima oră.",
    summary: "Tenantul administrat corect: licențe pe rol, MFA obligatoriu, acces condiționat, conturi privilegiate separate, offboarding automat. Identitatea e noul perimetru; o tratăm ca atare.",
    problems: ["Conturi ale foștilor angajați încă active.", "Licențe plătite și nefolosite; roluri de admin date „temporar” în 2022.", "Parole partajate pe e-mail."],
    included: ["Administrare Microsoft 365 / Google Workspace, politici de acces și partajare", "MFA obligatoriu și acces condiționat pe dispozitiv", "Onboarding/offboarding automat, cu listă de verificare", "Manager de parole al firmei, cu seifuri pe echipe", "Revizuire lunară a conturilor privilegiate și a licențelor"],
    proofs: ["Acoperire MFA (conturi cu / fără), zilnic", "Zero conturi orfane, verificat zilnic", "Licențe folosite vs. plătite"],
    kpis: [{ label: "MFA", value: "28/30" }, { label: "conturi orfane", value: "0" }, { label: "licențe folosite", value: "96%" }],
    now: "Politici de identitate ca standard, nu ca proiect.",
    future: "Identitatea devine singurul activ; dispozitivele sunt de unică folosință.",
    tags: ["M365", "Workspace", "MFA", "identitate"],
    tools: ["parole"],
  },
  {
    slug: "retea",
    name: "Rețea & Wi-Fi enterprise",
    tagline: "Segmentată, documentată, cu drum de rezervă. Scannerele nu mai cad „din senin”.",
    summary: "Rețele pe VLAN-uri cu reguli explicite între zone, firewall cu fiecare regulă justificată, Wi-Fi proiectat pe zone, VPN între sedii și legătură de rezervă comutată automat.",
    problems: ["Contabilitatea, depozitul și oaspeții în aceeași rețea.", "Reguli de firewall „temporare” de acum 4 ani.", "O pană de internet oprește tot."],
    included: ["Proiectare și segmentare (birou, servere, echipamente, oaspeți)", "Firewall administrat, reguli documentate și revizuite", "Wi-Fi enterprise cu roaming, proiectat pe zone", "VPN site-to-site și acces la distanță", "Legătură de rezervă 4G/5G cu comutare automată"],
    proofs: ["Hartă de rețea generată automat, la zi", "Fiecare regulă de firewall cu motiv, proprietar și dată", "Timp de comutare pe legătura de rezervă, testat lunar"],
    kpis: [{ label: "VLAN-uri", value: "4" }, { label: "reguli justificate", value: "60/60" }, { label: "failover", value: "< 60 s" }],
    now: "Rețeaua ca schemă vie, nu ca desen din 2021.",
    future: "Rețeaua devine invizibilă: fiecare conexiune e verificată criptografic, indiferent de loc.",
    tags: ["VLAN", "firewall", "Wi-Fi", "failover"],
    tools: ["simulator"],
  },
  {
    slug: "servere-virtualizare",
    name: "Servere, NAS & virtualizare",
    tagline: "Dimensionate corect, monitorizate permanent, cu imagine de restaurare gata.",
    summary: "Infrastructura on-prem tratată ca un sistem cu plan de viață: capacitate cu prognoză, garanții urmărite, patch-uri programate, imagine de restaurare testată, replică la cald acolo unde merită.",
    problems: ["Serverul „merge de 7 ani” și nimeni nu știe ce e pe el.", "Discul plin se descoperă când cade aplicația.", "Garanția a expirat acum 2 ani."],
    included: ["Proxmox / Hyper-V administrate, cu configurația versionată", "Monitorizare hardware (SMART, temperatură, alimentare) și capacitate", "Patch-uri în ferestre de mentenanță anunțate", "Imagine de restaurare completă, testată", "Plan de înlocuire pe 36 de luni, cu buget"],
    proofs: ["Utilizare și prognoză de capacitate pe 12 luni", "Garanții și vârste, cu alerte la 90 de zile", "Restaurare completă a unui server, demonstrată"],
    kpis: [{ label: "utilizare", value: "41%" }, { label: "prognoză plin", value: "> 24 luni" }, { label: "restore complet", value: "38 min" }],
    now: "Fiecare server are un plan de viață și un test de restaurare.",
    future: "Hardware-ul devine o utilitate; ce contează e ce rulează și cine îl poate atesta.",
    tags: ["Proxmox", "Hyper-V", "NAS", "capacitate"],
  },
  {
    slug: "backup-restaurare",
    name: "Backup & restaurare demonstrată",
    tagline: "Trei copii, două medii, una în altă locație, imutabilă. Și restaurări demonstrate lunar, cu cronometrul pornit.",
    summary: "Nu vindem backup; vindem restaurare. Lanțul 3-2-1 e criptat, copia offsite e imutabilă (ransomware-ul nu o poate atinge), iar în fiecare lună restaurăm efectiv ceva și consemnăm durata.",
    problems: ["Backup-ul „merge”, dar nu l-a restaurat nimeni niciodată.", "Copia de siguranță e pe același NAS pe care îl poate cripta ransomware-ul.", "E-mailurile șterse acum 6 luni nu mai există nicăieri."],
    included: ["Lanț 3-2-1 criptat, copie offsite imutabilă în regiuni UE", "Backup pentru Microsoft 365 / Google Workspace", "Restaurare demonstrată lunar (fișier, mașină virtuală, bază de date), cu durata consemnată", "Verificare de integritate zilnică", "Plan de recuperare cu RTO/RPO garantate, cu credite automate"],
    proofs: ["Ultima restaurare demonstrată: ce, când, cât a durat (DOV-…)", "Copia imutabilă: retenție și ultima verificare", "RPO efectiv (ore de la ultimul backup verificat), live"],
    kpis: [{ label: "ultimul restore", value: "7 min 12 s" }, { label: "RPO efectiv", value: "1 h" }, { label: "imutabil", value: "90 zile" }],
    now: "Restaurarea e un eveniment lunar programat, nu o urgență.",
    future: "Datele nu se mai „pierd”: fiecare stare a firmei e reconstruibilă, cu dovadă.",
    tags: ["3-2-1", "imutabil", "restore testat"],
    tools: ["risc-backup"],
  },
  {
    slug: "securitate",
    name: "Securitate măsurată",
    tagline: "Fără teatru, fără frică: 7 straturi, un scor zilnic, fiecare lipsă în lei.",
    summary: "Postura de securitate e un număr calculat zilnic din controale verificabile: identitate, dispozitive, rețea, e-mail, backup, monitorizare, răspuns. Fiecare control lipsă are un cost estimat, ca să decizi tu ce merită.",
    problems: ["„Avem antivirus” e tot ce știe managementul.", "Nimeni nu știe cine are acces la ce.", "Un e-mail bine scris poate muta o plată în alt cont."],
    included: ["Protecție endpoint administrată (EDR), cu răspuns la alerte", "Criptare disc, patch management în 14 zile, hardening standard", "SPF/DKIM/DMARC și proceduri anti-fraudă la plăți", "Simulări de phishing trimestriale, cu instruire de 10 minute", "Plan de răspuns la incident, exersat cu managementul"],
    proofs: ["Scor de postură (0–100) pe 7 straturi, zilnic", "Fiecare control: dovadă, dată, metodă", "Rezultatele simulărilor de phishing, pe echipă"],
    kpis: [{ label: "postură", value: "89/100" }, { label: "patch < 14 zile", value: "21/22" }, { label: "phishing (clic)", value: "4%" }],
    now: "Securitatea e o practică zilnică măsurată, nu un proiect anual.",
    future: "Fiecare acces are o dovadă criptografică; auditul e instantaneu.",
    tags: ["EDR", "MFA", "DMARC", "postură"],
    tools: ["email", "phishing", "web"],
  },
  {
    slug: "monitorizare",
    name: "Monitorizare cu semnal, nu zgomot",
    tagline: "Afli de la noi că ceva dă semne, nu de la colegi că nu mai merge.",
    summary: "Senzori pe servere, servicii, rețea, certificate și backup, cu alerte calibrate să nu depășească 5% zgomot. Alertele care au o rezolvare cunoscută nu ajung la oameni: se rezolvă și se consemnează.",
    problems: ["Afli că discul e plin când cade aplicația.", "Certificatul expiră duminică; site-ul afișează „nesigur” luni.", "Alertele sunt atât de multe încât nu le mai citește nimeni."],
    included: ["Monitorizare 24/7: servere, servicii, legături, Wi-Fi, certificate, domenii, backup", "Alerte calibrate, cu escaladare către oameni doar când e nevoie", "Registru de expirări (certificate, garanții, licențe, domenii) cu alerte la 90/30/7 zile", "Pagini de status pentru echipa ta", "Raport lunar de uptime per serviciu"],
    proofs: ["Uptime pe 30/90 de zile per serviciu, cu incidentele marcate", "Raport de zgomot: alerte relevante vs. total", "Timp de detecție (de la simptom la alertă)"],
    kpis: [{ label: "uptime 30 z", value: "99,98%" }, { label: "senzori", value: "37" }, { label: "zgomot", value: "7%" }],
    now: "Alertele trec prin auto-vindecare înainte să ajungă la oameni.",
    future: "Sistemele se repară înainte de simptom, pe baza semnalelor slabe.",
    tags: ["alerting", "metrici", "certificate", "uptime"],
  },
  {
    slug: "geaman-digital",
    name: "Geamăn digital & simulări",
    tagline: "Modelul viu al IT-ului tău. Întreabă „ce se întâmplă dacă…” înainte să se întâmple.",
    summary: "Fiecare echipament, cont, serviciu, legătură și furnizor devine un nod într-un graf cu dependențe explicite. Din graf derivăm cine e afectat de o cădere, cât durează revenirea, cât costă, și ce măsură merită banii.",
    problems: ["Nimeni nu știe ce se oprește dacă moare un anumit echipament.", "Bugetul de IT se decide pe intuiție.", "Punctele unice de eșec se descoperă la incident."],
    included: ["Geamănul digital construit la onboarding și actualizat automat", "Simulări de cădere pentru orice nod, cu impact în lei", "Registru de risc: pierdere anuală așteptată, inițială vs. reziduală", "Recomandări cu economie estimată și cost, ordonate", "Exerciții de incident conduse pe geamăn, cu managementul"],
    proofs: ["Registrul de risc lunar, în lei, cu ipotezele afișate", "Puncte unice de eșec: număr și plan pentru fiecare", "Fiecare recomandare: lei economisiți / an vs. cost"],
    kpis: [{ label: "risc rezidual", value: "≈ 21.000 lei/an" }, { label: "puncte unice de eșec", value: "2" }, { label: "scenarii simulate", value: "7" }],
    now: "Simulatorul e disponibil public, gratuit, în Instrumente.",
    future: "Fiecare schimbare e simulată automat în geamăn înainte să fie aplicată în realitate.",
    tags: ["graf", "simulare", "risc în lei"],
    tools: ["simulator", "audit-it"],
  },
  {
    slug: "automatizari-ai",
    name: "Automatizări & agenți AI",
    tagline: "Procese repetitive automatizate; AI acolo unde aduce timp înapoi și poate fi verificat.",
    summary: "De la fluxuri de onboarding la sincronizări între ERP și e-Factura, de la clasificarea solicitărilor la rapoarte generate. Fiecare automatizare are un proprietar, un jurnal și un buton de oprire.",
    problems: ["Aceleași date se introduc în trei sisteme.", "Rapoartele se fac manual, lunar, de aceeași persoană.", "„AI” înseamnă un chatbot care nu știe nimic despre firma ta."],
    included: ["Fluxuri de lucru automatizate (onboarding, aprobări, sincronizări, rapoarte)", "Agenți AI cu acces controlat la datele firmei, cu jurnal complet", "Integrări între ERP, Microsoft 365, e-Factura, CRM", "Fiecare automatizare: proprietar, test, buton de oprire", "Măsurarea orelor economisite, lunar"],
    proofs: ["Ore economisite / lună, per automatizare", "Jurnalul fiecărei acțiuni a unui agent, cu motivul", "Rata de eroare și rata de intervenție umană"],
    kpis: [{ label: "ore economisite", value: "46 / lună" }, { label: "automatizări active", value: "12" }, { label: "erori", value: "0,3%" }],
    now: "AI aplicat, verificabil, oprit cu un buton.",
    future: "Agenții negociază, planifică și repară; oamenii stabilesc limitele.",
    tags: ["automatizare", "agenți", "integrare"],
  },
  {
    slug: "aplicatii",
    name: "Aplicații interne, construite și operate",
    tagline: "Portaluri și aplicații pe Laravel sau Node, de echipa care le și ține în viață.",
    summary: "Construim aplicații interne mici și utile (portal de comenzi, aprobări, raportare) și le operăm ca pe restul infrastructurii: monitorizate, cu backup demonstrat, actualizate, cu cod și documentație predate.",
    problems: ["Aplicația internă făcută de un freelancer nu mai are pe nimeni care să o înțeleagă.", "Deploy-ul se face manual, vinerea.", "Nu există backup pentru baza de date a aplicației."],
    included: ["Dezvoltare Laravel / Node, cu cod în repository-ul tău", "Deploy automat, medii separate, backup și monitorizare", "Actualizări de securitate lunare", "Documentație și diagrame livrate cu fiecare versiune", "Operare inclusă, nu facturată la oră"],
    proofs: ["Uptime și timp de răspuns al aplicației", "Ultimul restore al bazei de date, demonstrat", "Vulnerabilități cunoscute: 0, verificat săptămânal"],
    kpis: [{ label: "deploy", value: "automat" }, { label: "uptime", value: "99,95%" }, { label: "cod predat", value: "100%" }],
    now: "Codul e al tău din prima zi, în repository-ul tău.",
    future: "Aplicațiile se generează din intenții; ce rămâne e operarea verificabilă.",
    tags: ["Laravel", "Node", "API", "operare"],
  },
  {
    slug: "consultanta",
    name: "Consultanță pentru management",
    tagline: "Decizii IT în lei: buget, riscuri, furnizori, plan pe 12 luni.",
    summary: "O oră pe lună cu managementul, cu registrul de risc pe masă: ce s-a schimbat, ce riscuri rămân, ce decizii cerem și cât costă fiecare opțiune. Planul IT pe 12 luni, cu buget, revizuit trimestrial.",
    problems: ["Bugetul de IT e o cifră moștenită.", "Furnizorii se schimbă când se enervează cineva.", "Nimeni nu poate răspunde la „cât ne-ar costa o zi fără sisteme?”"],
    included: ["Revizuire lunară de 45 de minute, pe registrul de risc", "Plan IT pe 12 luni, cu buget și priorități în lei", "Evaluare și negociere furnizori (internet, licențe, hardware)", "Pregătire pentru audituri (clienți, bănci, NIS2)", "Suport la decizii de creștere: sedii noi, fuziuni, aplicații"],
    proofs: ["Registrul deciziilor: ce s-a decis, când, pe ce cifre", "Buget planificat vs. realizat", "Riscul total: evoluție lunară, în lei"],
    kpis: [{ label: "risc redus", value: "−75%" }, { label: "buget vs. plan", value: "97%" }, { label: "decizii deschise", value: "2" }],
    now: "Fiecare recomandare vine cu o sumă și cu ipotezele ei.",
    future: "Managementul stabilește apetitul de risc; restul e delegat și verificat.",
    tags: ["strategie", "buget", "furnizori"],
    tools: ["cost-downtime", "calculator"],
  },
  {
    slug: "conformitate",
    name: "Conformitate, e-Factura & SPV",
    tagline: "GDPR fără panică, NIS2 fără consultanți scumpi, e-Factura fără erori la termen.",
    summary: "Cerințele legale traduse în controale verificabile pe care le avem oricum: acces, criptare, backup, jurnale. Pentru firmele de contabilitate și clienții lor: certificat SPV urmărit, transmiteri monitorizate, erori rezolvate.",
    problems: ["Certificatul SPV a expirat în ziua de raportare.", "Auditul clientului cere „politici” pe care nu le are nimeni scrise.", "GDPR înseamnă un document semnat în 2018."],
    included: ["Registru de controale mapat pe GDPR / NIS2 / cerințele clienților", "Politici scurte, reale, generate din configurația efectivă", "Monitorizare e-Factura / SPV, certificat reînnoit la timp, erori tratate", "Dovezi exportabile pentru audituri", "Notificare și plan în caz de incident cu date personale"],
    proofs: ["Controale conforme vs. total, per cadru", "Transmiteri e-Factura: reușite / eșuate / rezolvate, lunar", "Valabilitate certificat SPV, cu alerte"],
    kpis: [{ label: "controale conforme", value: "91%" }, { label: "e-Factura erori", value: "0 deschise" }, { label: "certificat SPV", value: "valid 118 z" }],
    now: "Conformitatea e un export din ce facem oricum, nu un proiect separat.",
    future: "Reglementările se verifică automat, continuu, de către terți.",
    tags: ["GDPR", "NIS2", "e-Factura", "SPV"],
  },
];

export function getCapability(slug: string): Capability | undefined {
  return capabilities.find((c) => c.slug === slug);
}
