#!/bin/bash
# Descarcă cele 20 ilustrații de domeniu public alese pentru volum.
# Rulează-l din folderul carte/ :  bash descarca-ilustratii.sh
# Wikimedia limitează rata pe IP-uri partajate; de pe o conexiune obișnuită merge instant.
set -e
mkdir -p ilustratii/fisiere
UA="IstoriaRomaniei-carte/1.0 (contact: mitza0704@gmail.com)"
echo "→ preistorie"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/preistorie.png" "https://upload.wikimedia.org/wikipedia/commons/9/9c/01894_Kronprinzenwerk%2C_Geschichte_B%C3%B6hmens_%281._Ab.%29%2C_Hallstatter_und_La_T%C3%A8ne_-Zeit_.._Opferwagen%2C_Schwerter%2C_Gef%C3%A4%C3%9Fe%2C_Fibeln%2C_Armringe_u.s.w._aus_Bronze.png"
echo "→ geti"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/geti.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/62/Cabeza_-_Ajuar_funerario_de_la_tumba_principesca_geta_de_Peretu.jpg"
echo "→ burebista"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/burebista.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/6e/Koson_-_M%C3%BCnzkabinett%2C_Berlin_-_5498176.jpg"
echo "→ burebista2"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/burebista2.jpg" "https://upload.wikimedia.org/wikipedia/commons/9/94/Murus_Dacicus.JPG"
echo "→ decebal"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/decebal.jpg" "https://upload.wikimedia.org/wikipedia/commons/0/06/Coloana_lui_Traian_%28detaliu%29.jpg"
echo "→ dacia-romana"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/dacia-romana.jpg" "https://upload.wikimedia.org/wikipedia/commons/8/8c/Milliarum_of_Aiton%2C_plaque_of_the_modern_copy_erected_in_Turda%2C_Romania_in_1993.jpg"
echo "→ migratii"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/migratii.jpg" "https://upload.wikimedia.org/wikipedia/commons/9/96/Tesaurul_de_la_Petrosa.jpg"
echo "→ voievodate"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/voievodate.jpg" "https://upload.wikimedia.org/wikipedia/commons/b/bf/Chronicon_Pictum_002.jpg"
echo "→ intemeiere"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/intemeiere.jpg" "https://upload.wikimedia.org/wikipedia/commons/f/f8/004_-_Basarab_I.jpg"
echo "→ cruciada"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/cruciada.jpg" "https://upload.wikimedia.org/wikipedia/commons/c/c0/Vlad_%C5%A2epe%C5%9F%2C_the_Impaler%2C_Prince_of_Wallachia_%281456-1462%29_%28died_1477%29.jpg"
echo "→ otoman"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/otoman.jpg" "https://upload.wikimedia.org/wikipedia/commons/2/2b/Portret_van_Mihai_Viteazul%2C_RP-P-OB-5054.jpg"
echo "→ fanarioti"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/fanarioti.jpg" "https://upload.wikimedia.org/wikipedia/commons/4/4e/Horja_and_Clocska.jpg"
echo "→ fanarioti2"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/fanarioti2.jpg" "https://upload.wikimedia.org/wikipedia/commons/e/ec/Principati1786.jpg"
echo "→ renastere"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/renastere.jpg" "https://upload.wikimedia.org/wikipedia/commons/d/df/CI_Stancescu_-_Alexandru_Ioan_Cuza.jpg"
echo "→ regat"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/regat.jpg" "https://upload.wikimedia.org/wikipedia/commons/0/0a/Frederic_Storck_-_Carol_I_-_1900_-_01.jpg"
echo "→ mare-razboi"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/mare-razboi.jpg" "https://upload.wikimedia.org/wikipedia/commons/1/1b/Romanian_troops_at_Marasesti_in_1917.jpg"
echo "→ interbelic"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/interbelic.jpg" "https://upload.wikimedia.org/wikipedia/commons/5/54/Extension_from_the_1930s_of_the_Adev%C4%83rul_Newspaper_Headquarter_on_Strada_Constantin_Mille%2C_Bucharest%2C_Romania%2C_with_an_Art_Deco_facade.jpg"
echo "→ razboi2"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/razboi2.jpg" "https://upload.wikimedia.org/wikipedia/commons/d/df/Beszterce%2C_Fa_utca_%28strada_Liviu_Rebreanu%29%2C_1940._szeptember_8._Fortepan_3953.jpg"
echo "→ minoritati"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/minoritati.jpg" "https://upload.wikimedia.org/wikipedia/commons/a/ac/Ethnographic_map_Ami_Bou%C3%A9%2C_1847.jpg"
echo "→ brancoveanu"
curl -sSL --max-time 180 -A "$UA" -o "ilustratii/fisiere/brancoveanu.jpg" "https://upload.wikimedia.org/wikipedia/commons/7/7d/Hurezi_Monastery_%28Horezu_region%29_%2811105605806%29.jpg"
echo
echo "Gata. Verific dimensiunile:"
ls -la ilustratii/fisiere/
