/* ===========================================================================
   SELECTIA MARE — peste doua sute de ilustratii, cu legendele lor.
   Formatul: [id din lista de candidati, capitolul, legenda].
   Capitolul "atlas" trimite in plansa cartografica de la sfarsitul volumului.
   =========================================================================== */
export const SELECTIE = [

/* ------------------------------ antichitate ------------------------------ */
['antichitate:1',  'burebista',    'Danubius Pannonico-Mysicus, ridicarea Dunarii facuta de contele Luigi Ferdinando Marsigli intre 1690 si 1700. Prima cercetare moderna a fluviului, cu observatii geografice, astronomice si arheologice.'],
['antichitate:0',  'dacia-romana', 'Theatrum antiquitatum Romanarum in Hungaria, 1727: antichitatile romane cunoscute la inceputul secolului al XVIII-lea, asezate pe harta.'],
['antichitate:15', 'decebal',      'Podul lui Traian si ruinele romane de la Dunare, plansa din Danubius Pannonico-Mysicus, 1726. Podul construit de Apollodor din Damasc a fost cea mai lunga constructie de acest fel din lumea romana.'],
['antichitate:10', 'decebal',      'Ramasitele turnului lui Severus si ale podului lui Traian peste Dunare, litografie de Bouquet, 1841. Pilonii erau inca vizibili in secolul al XIX-lea.'],
['antichitate:13', 'decebal',      'Inscriptia lui Traian de sub podul de la Drobeta, in reconstituirea lui Lodovico Pogliaghi.'],
['antichitate:17', 'decebal',      'Plansa LXXI din Conrad Cichorius, Die Reliefs der Traianssaule: seria de mulaje publicata intre 1896 si 1900 ramane editia de referinta a Columnei.'],
['antichitate:12', 'dacia-romana', 'Planul sapaturilor de la Ulpia Traiana Sarmizegetusa, 1872. Cercetarea sistematica a capitalei provinciei incepe in a doua jumatate a secolului al XIX-lea.'],
['antichitate:3',  'burebista',    'Bratara de aur de la Pipea, plansa din 1881. Piesele de acest tip au fost publicate in secolul al XIX-lea, cu mult inaintea descoperirilor de la Sarmizegetusa.'],
['antichitate:5',  'preistorie',   'Bratari de bronz descoperite la Maierus si la Atel, plansa din 1877. Metalurgia bronzului atinge in spatiul carpatic o densitate fara egal in Europa.'],
['antichitate:24', 'dacia-romana', 'Placuta votiva de plumb, secolul al III-lea, cu reprezentarea Cavalerilor Danubieni. Cultul, raspandit in provinciile dunarene, amesteca elemente trace, iraniene si romane.'],
['antichitate:19', 'atlas',        'Macedonia, Moesia, Thracia et Dacia, de Sidney Hall. Geografia antica redesenata in secolul al XIX-lea, cu nomenclatura latina suprapusa peste hotarele contemporane.'],
['antichitate:2',  'atlas',        'Provinciile romane Illyricum, Macedonia, Dacia, Moesia si Pannonia, plansa de atlas istoric, 1886.'],

/* -------------------------------- medieval ------------------------------- */
['medieval:0',     'intemeiere',   'Batalia de la Posada in Chronicon Pictum, c. 1360: ostenii lui Basarab arunca bolovani asupra coloanei maghiare prinse in defileu. Este singura reprezentare contemporana a evenimentului.'],
['medieval:34',    'intemeiere',   'Detaliu din scena Posadei: cavalerii lui Carol Robert, blocati intre pante, sunt loviti cu sageti si pietre. Cronica maghiara recunoaste infrangerea, ceea ce ii sporeste credibilitatea.'],
['medieval:1',     'intemeiere',   'A doua fila a Posadei in Chronicon Pictum. Regele scapa numai schimband hainele cu un ostean, care moare in locul lui.'],
['medieval:27',    'voievodate',   'Intrarea maghiarilor in bazinul carpatic, miniatura din Chronicon Pictum. Cronica este izvorul care a transmis si numele voievozilor infranti, disputati de istoriografie.'],
['medieval:10',    'voievodate',   'Geza al II-lea in regalia, Chronicon Pictum. In timpul domniei lui incepe colonizarea sasilor in Transilvania.'],
['medieval:22',    'voievodate',   'Primirea lui Andrei si orbirea lui Petru, miniatura din Chronicon Pictum: politica dinastica maghiara a secolului al XI-lea, in care se decide si soarta Transilvaniei.'],
['medieval:33',    'intemeiere',   'Manastirea Cozia vazuta de peste Olt, litografie de Lancelot, 1860. Ctitoria lui Mircea cel Batran, unde domnul este si ingropat.'],
['medieval:2',     'intemeiere',   'Manastirea Cozia in acuarela lui Amadeo Preziosi, 1869. Pictorul levantin a lasat cea mai bogata iconografie a Principatelor la mijlocul secolului al XIX-lea.'],
['medieval:35',    'cruciada',     'Manastirea Neamt, desen de G. Siller, c. 1850. Cel mai important centru de cultura al Moldovei medievale, cu scriptoriul in care s-au copiat cronicile.'],

/* ------------------------------- portrete -------------------------------- */
['portrete:1',     'otoman',       'Mihai Viteazul luptand cu turcii la Giurgiu, octombrie 1595, gravura tiparita in 1596. Stirea victoriei a circulat in Europa la cateva luni dupa eveniment.'],
['portrete:7',     'otoman',       'Batalia de la Guruslau, 3 august 1601, gravura de epoca. Victoria impotriva lui Sigismund Bathory a fost ultima a lui Mihai Viteazul; sase zile mai tarziu era ucis pe Campia Turzii.'],
['portrete:8',     'otoman',       'Alegorie a razboiului cu turcii: batalia de la Brasov, de Hans von Aachen, c. 1603. Pictorul de curte al lui Rudolf al II-lea a transformat campaniile transilvanene in program politic imperial.'],
['portrete:9',     'otoman',       'A doua alegorie a lui Hans von Aachen, cu batalia de la Sisak. Seria a fost comandata pentru a justifica efortul de razboi al Habsburgilor.'],
['portrete:10',    'cruciada',     'Campania cea Lunga a lui Iancu de Hunedoara, miniatura din Cronica lui Thuroczy, 1488. Expeditia din 1443-1444 a dus armata crestina pana in Balcani.'],
['portrete:5',     'cruciada',     'Diploma de innobilare a lui Iancu de Hunedoara, data de Ladislau al V-lea in februarie 1453. Actul consfinteste ascensiunea unei familii de cnezi romani in varful nobilimii maghiare.'],
['portrete:71',    'cruciada',     'Blazonul acordat familiei Hunyadi prin diploma din 1453, cu corbul care avea sa dea numele dinastiei Corvinilor.'],
['portrete:25',    'brancoveanu',  'Moneda de aur de zece ducati a principelui Gabriel Bethlen, Transilvania, 1616. Emisiunile mari de aur erau instrumente de prestigiu si de plata a mercenarilor.'],
['portrete:26',    'brancoveanu',  'Moneda de aur de douazeci si cinci de ducati a principelui Mihail Apafi, 1681. Principatul isi bate propria moneda si sub suzeranitate otomana.'],
['portrete:64',    'otoman',       'Moneda de necesitate batuta de Gabriel Bathory in timpul asediului Sibiului, 1611: metalul de la fata locului, taiat in graba, ca plata pentru trupe.'],
['portrete:77',    'otoman',       'Moneda lui Gabriel Bathory, 1609.'],
['portrete:73',    'brancoveanu',  'Mihail Apafi, principe al Transilvaniei, c. 1670. Ultimul principe autonom inainte de trecerea sub stapanirea habsburgica.'],
['portrete:24',    'brancoveanu',  'Dimitrie Cantemir, portret din Descriptio Moldaviae, 1716. Domn pentru cateva luni, apoi exilat in Rusia, a devenit primul membru roman al Academiei din Berlin.'],
['portrete:21',    'brancoveanu',  'Dimitrie Cantemir in gravura olandeza din 1735. Reputatia lui europeana s-a construit pe scrierile de istorie otomana, nu pe scurta lui domnie.'],
['portrete:27',    'brancoveanu',  'Pagina de titlu a lucrarii The History of the Growth and Decay of the Othman Empire, Londra, 1734-1735. Tradusa din latina, cartea lui Cantemir a fost timp de un secol lucrarea de referinta a europenilor despre Imperiul Otoman.'],
['portrete:68',    'brancoveanu',  'Hronicul vechimei a romano-moldo-vlahilor, scris de Cantemir intre 1717 si 1723: prima incercare sistematica de a demonstra originea latina si unitatea romanilor.'],
['portrete:52',    'fanarioti',    'Reveria principelui Dimitrie Cantemir, gravura din 1788. Figura domnului-savant a intrat in imaginarul iluminist european.'],
['portrete:51',    'brancoveanu',  'Stema lui Constantin Brancoveanu, 1700. Domnia lui de douazeci si sase de ani a fost cea mai lunga din istoria Tarii Romanesti.'],
['portrete:72',    'fanarioti',    'Asediul si cucerirea Iasilor, 1788, gravura contemporana. Razboiul austro-ruso-turc a purtat frontul prin mijlocul Moldovei.'],
['portrete:0',     'otoman',       'Ocupatia otomana a partii centrale a regatului maghiar, harta din 1629: Transilvania ramane principat autonom intre doua imperii.'],
['portrete:30',    'renastere',    'Alexandru Ioan Cuza, fotografie de Carol Popp de Szathmary. Szathmary a fost unul dintre cei dintai fotografi de razboi din lume.'],
['portrete:66',    'renastere',    'Alexandru Ioan Cuza inainte de 1866.'],
['portrete:61',    'renastere',    'Deschiderea Adunarii legiuitoare de catre Cuza, 29 februarie 1860.'],
['portrete:55',    'renastere',    'Cuza si doctorul Carol Davila viziteaza mahalaua Tabaci, inundata in 1862. Davila a intemeiat invatamantul medical romanesc.'],
['portrete:34',    'regat',        'Juramantul lui Carol I, 1866. Principele de Hohenzollern-Sigmaringen a ajuns in tara calatorind sub nume fals, pe Dunare.'],
['portrete:70',    'regat',        'Carol I inmaneaza drapelele Garzii Civice, 11 septembrie 1867.'],
['portrete:29',    'regat',        'Carol I la Slanic Moldova, 1891.'],
['portrete:19',    'mare-razboi',  'Funeraliile lui Carol I, 1914. Regele a murit la doua luni dupa izbucnirea razboiului, dupa ce Consiliul de Coroana ii respinsese cererea de a intra alaturi de Puterile Centrale.'],
['portrete:23',    'interbelic',   'Marioara si Carol al II-lea, fotografie de la inceputul secolului al XX-lea.'],
['portrete:63',    'regat',        'Membrii Junimii, 1883. Societatea iesenilor a dat tara doi prim-ministri, o teorie critica influenta si cea mai importanta revista literara a epocii.'],
['portrete:54',    'regat',        'Ex-librisul lui Ion Creanga, 1878.'],
['portrete:6',     'renastere',    'Sasa Cuza, c. 1889. Unul dintre cei doi fii pe care Alexandru Ioan Cuza i-a avut cu Maria Obrenovici si pe care Elena Cuza i-a crescut ca pe ai ei, dupa abdicare, in exilul de la Heidelberg.'],

/* ------------------------------- tiparituri ------------------------------ */
['tiparituri:7',   'brancoveanu',  'Fila din Codicele de la Ieud, c. 1630, unul dintre cele mai vechi manuscrise romanesti pastrate, scris cu litere chirilice.'],
['tiparituri:19',  'brancoveanu',  'Alta fila din Codicele de la Ieud. Textele religioase in limba romana incep sa circule in secolul al XVII-lea, inlocuind treptat slavona.'],
['tiparituri:12',  'brancoveanu',  'Pagina din Codicele de la Ieud, cu initiale ornate in traditia manuscriselor slavone.'],
['tiparituri:0',   'religie',      'Pomelnicul lui Nicolae Iovepali si al familiei sale de la schitul Cuvioasa Parascheva, c. 1800: lista mortilor pomeniti la slujba, principalul document de istorie a familiilor tarzii.'],
['tiparituri:1',   'religie',      'Ingroparea lui Avel, tipatura chirilica din 1818.'],
['tiparituri:3',   'limba',        'Alfabetul chirilic romanesc in forma lui tarzie, dupa Vasile Alecsandri, 1863. Trecerea oficiala la litere latine se face intre 1860 si 1862.'],
['tiparituri:5',   'renastere',    'Antet al Eforiei Spitalelor Civile din Principatele Unite, 1859, cu grafie chirilica si titulatura noului stat.'],
['tiparituri:6',   'renastere',    'Mozaicul, revista aparuta la Craiova la 3 octombrie 1838. Presa in limba romana se inmulteste rapid dupa Regulamentele Organice.'],
['tiparituri:2',   'orase',        'Stema Iasilor, 1834.'],

/* --------------------------------- sec19 --------------------------------- */
['sec19:43',       'regat',        'Trecerea Dunarii la Corabia, de Nicolae Grigorescu, 1877. Pictorul a insotit armata ca martor oficial al campaniei.'],
['sec19:42',       'regat',        'Podul militar de vase peste Dunare, de la Silistioara la Magura, 1877.'],
['sec19:19',       'regat',        'Atacul de la Smardan, de Nicolae Grigorescu. Tabloul a devenit imaginea canonica a Razboiului de Independenta.'],
['sec19:1',        'regat',        'Redutele Grivitei, 1881. Asaltul din 30 august 1877 a costat armata romana peste o mie de morti intr-o singura zi.'],
['sec19:33',       'regat',        'La Plevna, de Theodor Aman. Asediul a durat cinci luni si a decis soarta razboiului.'],
['sec19:23',       'regat',        'Spionul, de Nicolae Grigorescu. Din campania din 1877 pictorul a adus mai putine scene de batalie si mai multe figuri de oameni.'],
['sec19:21',       'regat',        'Rosiorul, de Nicolae Grigorescu.'],
['sec19:24',       'regat',        'Convoi de prizonieri, de Nicolae Grigorescu.'],
['sec19:26',       'regat',        'Parada la Nicopole, de Nicolae Grigorescu.'],
['sec19:3',        'regat',        'Pomenirea eroilor pe campiile Bulgariei, de Nicolae Grigorescu.'],
['sec19:0',        'regat',        'Armata rusa la Bucuresti, The Illustrated London News, octombrie 1877. Trecerea trupelor tariste prin tara a precedat intrarea Romaniei in razboi.'],
['sec19:34',       'regat',        'Sosirea la Bucuresti a marelui duce Nicolae, comandantul armatei ruse, 1877.'],
['sec19:5',        'regat',        'Explozia monitorului otoman Lutfi Djelil la Braila, 1877. Scufundarea navei a deschis Dunarea pentru trupele aliate.'],
['sec19:11',       'regat',        'Monumentul comemorativ de la Rahova, 1902.'],
['sec19:16',       'regat',        'Actul proclamarii Regatului Romaniei, 1881.'],
['sec19:17',       'regat',        'Incoronarea lui Carol I ca rege, 1881. Coroana a fost turnata din otelul unui tun otoman capturat la Plevna.'],
['sec19:25',       'regat',        'Regele Carol I cu suita, fotografie de Carol Popp de Szathmary, 1881.'],
['sec19:14',       'atlas',        'Romania la 1887, harta a Regatului dupa dobandirea Dobrogei.'],
['sec19:15',       'minoritati',   'Harta etnica a Austro-Ungariei si a Romaniei, 1892. Cartografia etnica devine, in ultimele decenii ale secolului al XIX-lea, un instrument al revendicarilor nationale.'],
['sec19:12',       'mare-razboi',  'Romania Mare, harta publicata de The New York Times la 10 august 1919, in timpul Conferintei de Pace.'],
['sec19:13',       'regat',        'Calea ferata Lemberg-Cernauti-Iasi-Buzau-Marasesti, plansa din 1881. Reteaua feroviara a legat Principatele de pietele europene si a schimbat geografia economica a tarii.'],
['sec19:32',       'orase',        'Biserica lui Bucur, 1882. Traditia o leaga de legenda intemeierii Bucurestiului, fara temei documentar.'],

/* ----------------------------- orase si viata ---------------------------- */
['orase-vechi:27', 'romi',         'Anunt de vanzare a doua sute de familii de tigani, 1845. Robia romilor a fost desfiintata abia in 1855 in Moldova si in 1856 in Tara Romaneasca, iar fostii robi nu au fost improprietariti.'],
['orase-vechi:18', 'orase',        'Bucurestiul, capitala Valahiei, gravura publicata la 13 septembrie 1856.'],
['orase-vechi:30', 'orase',        'Tramvaiul cu cai din Bucuresti, 1871.'],
['orase-vechi:33', 'orase',        'Gara de Nord din Bucuresti inainte de 1900.'],
['orase-vechi:14', 'orase',        'Piata Sfatului din Brasov, 1848. Orasele sasesti au pastrat cel mai bine structura medievala: piata centrala, casa sfatului, ziduri de breasla.'],
['orase-vechi:16', 'orase',        'Clujul in Civitates orbis terrarum al lui Braun si Hogenberg, 1617.'],
['orase-vechi:21', 'orase',        'Clujul dupa Jan Peeters, 1685.'],
['orase-vechi:24', 'orase',        'Clujul in desenul lui Conrad von Weiss, 1735.'],
['orase-vechi:19', 'orase',        'Panorama Clujului, c. 1840.'],
['orase-vechi:6',  'orase',        'Timisoara in jurul anului 1720, la scurt timp dupa cucerirea austriaca a Banatului.'],
['orase-vechi:5',  'orase',        'Planul cetatii Timisoara, 1775.'],
['orase-vechi:32', 'orase',        'Strada Titu Maiorescu din Timisoara, inainte de 1899.'],
['orase-vechi:31', 'orase',        'Biserica Milenara din Timisoara, ridicata intre 1896 si 1899.'],
['orase-vechi:28', 'orase',        'Targ in Transilvania, acuarela de Lanzedelli, 1818.'],
['orase-vechi:29', 'renastere',    'Alexandru Lapusneanul de Costache Negruzzi, in editia din 1840, cu litere chirilice. Nuvela a fixat in literatura romana imaginea domnului tiran.'],
['orase-vechi:26', 'cultura',      'Prima pagina a revistei Convorbiri Literare, 1 mai 1885. In paginile ei au aparut Eminescu, Creanga, Caragiale si Slavici.'],
['orase-vechi:40', 'mare-razboi',  'Constanta in septembrie 1916, dupa ocuparea orasului de trupele Puterilor Centrale.'],
['orase-vechi:38', 'interbelic',   'Palat bucurestean, fotografie din 1923. Contrastul dintre capitala si satul romanesc a fost tema centrala a dezbaterii interbelice.'],
['orase-vechi:39', 'minoritati',   'Copii tarani in camasa alba si iie cusuta, fotografie din reportajul National Geographic despre Romania, 1923. Costumul de sarbatoare era tesut si cusut in gospodarie, iar motivele se citeau ca un act de identitate: sat, varsta, stare civila.'],
['orase-vechi:37', 'orase',        'Birjar bucurestean, 1923.'],

/* --------------------------------- sec20 --------------------------------- */
['sec20:16',       'mare-razboi',  'Fotografie de pe frontul romanesc, 1916-1917, din albumul daruit de generalul Rudianu. Campania din 1916 s-a incheiat cu pierderea a trei sferturi din teritoriu.'],
['sec20:18',       'mare-razboi',  'Trupe romane pe front, 1916.'],
['sec20:14',       'mare-razboi',  'Inspectarea unui obuz neexplodat cazut in transeele romanesti, 6 mai 1916.'],
['sec20:27',       'mare-razboi',  'Gara Predeal distrusa de bombardamentul Puterilor Centrale, 1916.'],
['sec20:25',       'mare-razboi',  'Retele de sarma ghimpata pe frontul din Moldova, iarna 1917. Dupa retragerea la Iasi, frontul s-a stabilizat pe linia Siretului.'],
['sec20:41',       'mare-razboi',  'Bucurestiul bombardat din zeppelin, 1916.'],
['sec20:39',       'mare-razboi',  'Efectele bombardamentelor aeriene asupra Bucurestiului, 1916.'],
['sec20:6',        'mare-razboi',  'Sediul guvernamantului imperial al Bucurestiului, 1916-1918, in timpul ocupatiei germane.'],
['sec20:40',       'mare-razboi',  'Generalul german Eberhard von Schmettow, comandant in Romania ocupata.'],
['sec20:47',       'mare-razboi',  'Demonstratie la Bucuresti in favoarea intrarii in razboi, 1915-1916. Tara a ramas neutra doi ani, sub presiunea celor doua tabere.'],
['sec20:31',       'mare-razboi',  'Muncitoarele fabricii de paste din Galati protesteaza impotriva razboiului, c. august 1916.'],
['sec20:35',       'mare-razboi',  'Regele Ferdinand depune juramantul.'],
['sec20:0',        'razboi2',      'Bistrita, strada Liviu Rebreanu, septembrie 1940: intrarea trupelor maghiare in nordul Transilvaniei cedat prin Dictatul de la Viena. Fotografie color de epoca.'],
['sec20:1',        'razboi2',      'Piata centrala a Clujului in ziua intrarii trupelor maghiare, cu biserica Sfantul Mihail in fundal, septembrie 1940.'],
['sec20:3',        'razboi2',      'Nasaud, 1940: fotografie de grup la intrarea trupelor maghiare. Populatia maghiara a primit schimbarea ca eliberare, cea romaneasca drept catastrofa.'],
['sec20:8',        'razboi2',      'Nordul Transilvaniei, septembrie 1940.'],
['sec20:9',        'razboi2',      'Nordul Transilvaniei, septembrie 1940: sateni in costum popular asteptand pe marginea drumului.'],
['sec20:11',       'razboi2',      'Un steag cu inscriptia Siebenbuergen unsere Heimat, purtat de comunitatea sasa la intrarea trupelor maghiare, 1940.'],
['sec20:13',       'razboi2',      'Nordul Transilvaniei, 1940.'],
['sec20:15',       'razboi2',      'Trupe maghiare intrand intr-o localitate din nordul Transilvaniei, 1940.'],
['sec20:5',        'razboi2',      'Primirea armatei maghiare la Ilonda, 8 septembrie 1940.'],
['sec20:23',       'evrei',        'Publicatie a Primariei Pascani, 4 iulie 1941: evreii gasiti pe strada intre orele 18 si 7 urmau sa fie executati, primii dintre ei ostaticii aflati deja in arest. Documentul arata cum a functionat administrativ persecutia.'],
['sec20:29',       'evrei',        'Grupuri de participanti la pogromul din Bucuresti, ianuarie 1941. In timpul rebeliunii legionare au fost ucisi o suta douazeci si unu de evrei.'],
['sec20:26',       'evrei',        'La Podul Sabarului, ianuarie 1941: locul unde au fost duse si ucise o parte dintre victimele pogromului bucurestean.'],
['sec20:30',       'evrei',        'Cadavru neidentificat scos din canalul colector al Abatorului, ianuarie 1941. La abatorul din Bucuresti au fost ucisi evrei in timpul rebeliunii legionare.'],
['sec20:42',       'evrei',        'Templul Spaniol din Bucuresti, ianuarie 1941, dupa devastarea din timpul rebeliunii legionare.'],
['sec20:49',       'evrei',        'Bucuresti, 21-23 ianuarie 1941: rebeliunea legionara, inabusita de armata la ordinul lui Antonescu.'],
['sec20:21',       'evrei',        'Proviziile lui Radu Lecca, imputernicitul guvernului pentru problemele evreiesti, platite de Centrala Evreilor, 1943. Institutia impusa comunitatii a fost folosita si pentru a-i extrage bani.'],
['sec20:37',       'evrei',        'Sedinta literara la Baraseum, 1943. Teatrul evreiesc din Bucuresti a functionat in anii interzicerii evreilor din viata publica.'],
['sec20:22',       'razboi2',      'Act de identitate pentru refugiat polonez, eliberat la Bucuresti in 1943. Prin Romania au trecut zeci de mii de refugiati polonezi dupa septembrie 1939.'],
['sec20:44',       'evrei',        'Selectia copiilor inaintea eliberarii lor din Transnistria, 1944. Repatrierea orfanilor a inceput dupa ce guvernul Antonescu a schimbat cursul politicii sale.'],
['sec20:45',       'razboi2',      'Odesa in 1942, sub administratie romaneasca. Orasul a fost capitala Transnistriei intre 1941 si 1944.'],
['sec20:46',       'razboi2',      'Opera din Odesa in 1942.'],
['sec20:50',       'razboi2',      'Intrarea trupelor romane intoarse de la Odesa pe Calea Victoriei, 8 noiembrie 1941.'],
['sec20:48',       'razboi2',      'Operatiunea Iasi-Chisinau, august 1944: ofensiva sovietica ce a dus la prabusirea frontului si la actul de la 23 august.'],
['sec20:34',       'romi',         'Tara Noastra, editie speciala saptamanala pentru romii din Romania, 1 august 1937. Presa romilor apare in anii 1930, odata cu Uniunea Generala a Romilor.'],
['sec20:32',       'interbelic',   'Cuvantul Liber, 1935: presa Frontului Popular, intr-un deceniu in care extrema dreapta castiga teren.'],
['sec20:36',       'interbelic',   'Caricatura care ii ia in ras pe A. C. Cuza si pe Ion I. C. Bratianu, februarie 1923. Anul Constitutiei este si anul in care antisemitismul universitar devine miscare de masa.'],
['sec20:7',        'interbelic',   'Garda zdrentaroasa la proclamarea Lajtabansag, 4 octombrie 1921: revizionismul maghiar imediat postbelic.'],

/* ============================ plansa cartografica ======================== */
['harti:29',       'atlas',        'Ungaria impartita in trei, 1567: regatul habsburgic, pasalacul de Buda si principatul Transilvaniei, configuratia care a facut posibila autonomia transilvaneana.'],
['harti:71',       'atlas',        'Transilvania la 1572.'],
['harti:84',       'atlas',        'Transilvania in Cosmographia lui Sebastian Munster, una dintre cele dintai reprezentari tiparite ale provinciei.'],
['harti:0',        'atlas',        'Romania, quae olim Thracia dicta, si regiunile vecine, Basel, 1584, colorata de mana.'],
['harti:15',       'atlas',        'Walachia, Servia, Bulgaria, Romania, de Gerard Mercator, 1589: prima harta moderna dedicata special spatiului dintre Carpati si Balcani.'],
['harti:7',        'atlas',        'Walachia, Servia, Bulgaria, Romania, editia din 1594 a hartii lui Mercator.'],
['harti:9',        'atlas',        'Daciarum Moesiarumque vetus descriptio, de Abraham Ortelius: geografia antica reconstituita dupa izvoarele scrise.'],
['harti:50',       'atlas',        'Transilvania, de Gerard Mercator, editia din 1606.'],
['harti:55',       'atlas',        'Transilvania, de Abraham Ortelius, 1612.'],
['harti:30',       'atlas',        'Dacia si Moesia, de Abraham Ortelius, c. 1608.'],
['harti:13',       'atlas',        'Vetus descriptio Daciarum nec non Moesiarum, de Petrus Kaerius.'],
['harti:43',       'atlas',        'Transilvania, c. 1627.'],
['harti:48',       'atlas',        'Transilvania, dupa Mercator, editie de la sfarsitul anilor 1620.'],
['harti:3',        'atlas',        'Walachia, Servia, Bulgaria, Romania, editia din 1630.'],
['harti:12',       'atlas',        'Aceeasi harta in editia din 1640, semn al longevitatii modelului mercatorian.'],
['harti:31',       'atlas',        'Valahia intr-o reprezentare din 1643.'],
['harti:77',       'atlas',        'Walachia, Servia, Bulgaria, Romania, in atlasul lui Joan Blaeu, 1645.'],
['harti:36',       'atlas',        'Cursul Dunarii, 1665.'],
['harti:64',       'atlas',        'Cartus ornamental dintr-o harta a Dunarii de Nicolas Sanson, 1665.'],
['harti:54',       'atlas',        'La Transilvanie ou Sibenburgen, 1668.'],
['harti:19',       'atlas',        'Walachia, Seruia, Bulgaria, Romania, editie de dupa 1673.'],
['harti:42',       'atlas',        'Principatul Transilvaniei impartit in cinci natiuni, 1691. Impartirea juridica in natiuni privilegiate a exclus populatia romaneasca majoritara.'],
['harti:20',       'atlas',        'Exactissima Tabula a cursului inferior al Dunarii, c. 1700.'],
['harti:27',       'atlas',        'Transilvania si Moldova, de De La Feuille, 1710.'],
['harti:28',       'atlas',        'Imperiul Oriental si regiunile invecinate, de Banduri si Delisle, c. 1715, cu Moldova si Valahia ca entitati distincte.'],
['harti:6',        'atlas',        'Ukrania quae et terra cosaccorum, cu Valahia si Moldova invecinate, de Johann Baptist Homann, 1724.'],
['harti:53',       'atlas',        'Tabula Valachiae Cisalutanae, 1722: Oltenia sub stapanire austriaca, intre 1718 si 1739.'],
['harti:74',       'atlas',        'Fragment heraldic din harta Valahiei Cisalutane, 1723.'],
['harti:68',       'atlas',        'Harta miniera a nordului Transilvaniei, din Danubius Pannonico-Mysicus, 1726. Aurul Apusenilor a fost motivul economic al tuturor stapanirilor din regiune.'],
['harti:33',       'atlas',        'Turcia europeana, cu regiunile romanesti, de Herman Moll, 1726.'],
['harti:47',       'atlas',        'Principatul Transilvaniei impartit in cinci natiuni, editia din 1742.'],
['harti:4',        'atlas',        'Transylvaniae principatus in quinque nationes divisus, 1757, colorata de mana.'],
['harti:34',       'atlas',        'Tabula geographica continens Despotatus Wallachiae atque Moldaviae, 1769.'],
['harti:67',       'atlas',        'Ridicarea topografica iozefina a Banatului, 1769-1772: prima cartografiere sistematica, militara, a regiunii.'],
['harti:37',       'atlas',        'Siebenburgen, harta din 1789.'],
['harti:18',       'atlas',        'Ungaria si Transilvania, de Laurie si Whittle, 1794.'],
['harti:45',       'atlas',        'Harta generala a Valahiei, de Rigas Velestinlis, 1797. Cartograful grec, executat de otomani in 1798, o concepuse ca instrument al unei insurectii balcanice.'],
['harti:72',       'atlas',        'Harta Romaniei de Daniel Philippidis, 1816. Philippidis este cel care a impus in greaca numele de Romania pentru ansamblul celor doua principate.'],
['harti:2',        'atlas',        'Schita militara a tinutului dintre Dunare si Constantinopol, 1828, ridicata in timpul razboiului ruso-turc.'],
['harti:21',       'atlas',        'Imperiul Austriac, de Pinkerton, 1818, colorata de mana.'],
['harti:63',       'atlas',        'Planul Bucurestiului intocmit de Vladimir de Blaremberg, 1842.'],
['harti:56',       'atlas',        'Dunarea de Jos, 1853.'],
['harti:52',       'atlas',        'Marele Principat al Transilvaniei dupa noua impartire politica, 1854.'],
['harti:39',       'atlas',        'Principatele Dunarene, c. 1854, intocmite dupa harta de la Viena, in ajunul Razboiului Crimeii.'],
['harti:24',       'atlas',        'Turcia europeana, Macedonia si Balcanii, de Colton, 1855.'],
['harti:46',       'atlas',        'Planul Bucurestiului ridicat de maiorul Dimitrie Pappasoglu, 1871.'],
['harti:51',       'atlas',        'Roumanie, 1886: Vechiul Regat la opt ani dupa recunoasterea independentei, cu Dobrogea adaugata si cu judetele din sudul Basarabiei pierdute. Harta franceza arata si reteaua de cai ferate abia terminata.'],
['harti:11',       'atlas',        'Valahia, gurile Dunarii si vestul Transilvaniei, plansa din harta Scheda a Europei, c. 1860.'],
['harti:88',       'atlas',        'Harta generala a Imperiului Austriac, de Joseph von Scheda: cartografia militara austriaca a fost cea mai precisa a secolului al XIX-lea in regiune.'],
['harti:81',       'atlas',        'Sibiul in ridicarea topografica austriaca.'],
['harti:78',       'atlas',        'Segment din Tabula Peutingeriana cu Moesia Inferior de rasarit: copie medievala a unui itinerar rutier roman.'],
['harti:79',       'atlas',        'Segment din Tabula Peutingeriana cu Moesia Inferior de apus.'],
['harti:73',       'atlas',        'Harta Moldovei din Descriptio Moldaviae a lui Dimitrie Cantemir: prima harta a tarii intocmita de un roman.'],
]
