/* ===========================================================================
   SELECTIA MARE — peste doua sute de ilustratii, cu legendele lor.
   Formatul: [id din lista de candidati, capitolul, legenda].
   Capitolul "atlas" trimite in plansa cartografica de la sfarsitul volumului.
   =========================================================================== */
export const SELECTIE = [

/* ------------------------------ antichitate ------------------------------ */
['antichitate:1',  'burebista',    'Danubius Pannonico-Mysicus, ridicarea Dunării făcută de contele Luigi Ferdinando Marsigli între 1690 și 1700. Prima cercetare modernă a fluviului, cu observații geografice, astronomice și arheologice.'],
['antichitate:0',  'dacia-romana', 'Theatrum antiquitatum Romanarum in Hungaria, 1727: antichitățile romane cunoscute la începutul secolului al XVIII-lea, așezate pe hartă.'],
['antichitate:15', 'decebal',      'Podul lui Traian și ruinele romane de la Dunăre, planșa din Danubius Pannonico-Mysicus, 1726. Podul construit de Apollodor din Damasc a fost cea mai lungă construcție de acest fel din lumea romană.'],
['antichitate:10', 'decebal',      'Rămășițele turnului lui Severus și ale podului lui Traian peste Dunăre, litografie de Bouquet, 1841. Pilonii erau încă vizibili în secolul al XIX-lea.'],
['antichitate:13', 'decebal',      'Inscripția lui Traian de sub podul de la Drobeta, în reconstituirea lui Lodovico Pogliaghi.'],
['antichitate:17', 'decebal',      'Planșa LXXI din Conrad Cichorius, Die Reliefs der Traianssäule: seria de mulaje publicată între 1896 și 1900 rămâne ediția de referință a Columnei.'],
['antichitate:12', 'dacia-romana', 'Planul săpăturilor de la Ulpia Traiana Sarmizegetusa, 1872. Cercetarea sistematică a capitalei provinciei începe în a doua jumătate a secolului al XIX-lea.'],
['antichitate:3',  'burebista',    'Brățara de aur de la Pipea, planșa din 1881. Piesele de acest tip au fost publicate în secolul al XIX-lea, cu mult înaintea descoperirilor de la Sarmizegetusa.'],
['antichitate:5',  'preistorie',   'Brățări de bronz descoperite la Măieruș și la Atel, planșa din 1877. Metalurgia bronzului atinge în spațiul carpatic o densitate fără egal în Europa.'],
['antichitate:24', 'dacia-romana', 'Plăcuța votivă de plumb, secolul al III-lea, cu reprezentarea Cavalerilor Danubieni. Cultul, răspândit în provinciile dunărene, amestecă elemente trace, iraniene și romane.'],
['antichitate:19', 'atlas',        'Macedonia, Moesia, Thracia et Dacia, de Sidney Hall. Geografia antică redesenată în secolul al XIX-lea, cu nomenclatura latină suprapusă peste hotarele contemporane.'],
['antichitate:2',  'atlas',        'Provinciile romane Illyricum, Macedonia, Dacia, Moesia și Pannonia, planșa de atlas istoric, 1886.'],

/* -------------------------------- medieval ------------------------------- */
['medieval:0',     'intemeiere',   'Bătălia de la Posada în Chronicon Pictum, c. 1360: ostenii lui Basarab aruncă bolovani asupra coloanei maghiare prinse în defileu. Este singura reprezentare contemporană a evenimentului.'],
['medieval:34',    'intemeiere',   'Detaliu din scena Posadei: cavalerii lui Carol Robert, blocați între pante, sunt loviți cu săgeți și pietre. Cronica maghiară recunoaște înfrângerea, ceea ce îi sporește credibilitatea.'],
['medieval:1',     'intemeiere',   'A doua filă a Posadei în Chronicon Pictum. Regele scapă numai schimbând hainele cu un oștean, care moare în locul lui.'],
['medieval:27',    'voievodate',   'Intrarea maghiarilor în bazinul carpatic, miniatură din Chronicon Pictum. Cronica este izvorul care a transmis și numele voievozilor înfrânți, disputați de istoriografie.'],
['medieval:10',    'voievodate',   'Géza al II-lea în regalia, Chronicon Pictum. În timpul domniei lui începe colonizarea sașilor în Transilvania.'],
['medieval:22',    'voievodate',   'Primirea lui Andrei și orbirea lui Petru, miniatură din Chronicon Pictum: politica dinastică maghiară a secolului al XI-lea, în care se decide și soarta Transilvaniei.'],
['medieval:33',    'intemeiere',   'Mănăstirea Cozia văzută de peste Olt, litografie de Lancelot, 1860. Ctitoria lui Mircea cel Bătrân, unde domnul este și îngropat.'],
['medieval:2',     'intemeiere',   'Mănăstirea Cozia în acuarela lui Amadeo Preziosi, 1869. Pictorul levantin a lăsat cea mai bogată iconografie a Principatelor la mijlocul secolului al XIX-lea.'],
['medieval:35',    'cruciada',     'Mănăstirea Neamț, desen de G. Siller, c. 1850. Cel mai important centru de cultură al Moldovei medievale, cu scriptoriul în care s-au copiat cronicile.'],

/* ------------------------------- portrete -------------------------------- */
['portrete:1',     'otoman',       'Mihai Viteazul luptând cu turcii la Giurgiu, octombrie 1595, gravură tipărită în 1596. Știrea victoriei a circulat în Europa la câteva luni după eveniment.'],
['portrete:7',     'otoman',       'Bătălia de la Guruslău, 3 august 1601, gravură de epocă. Victoria împotriva lui Sigismund Báthory a fost ultima a lui Mihai Viteazul; șase zile mai târziu era ucis pe Câmpia Turzii.'],
['portrete:8',     'otoman',       'Alegorie a războiului cu turcii: bătălia de la Brașov, de Hans von Aachen, c. 1603. Pictorul de curte al lui Rudolf al II-lea a transformat campaniile transilvănene în program politic imperial.'],
['portrete:9',     'otoman',       'A doua alegorie a lui Hans von Aachen, cu bătălia de la Sisak. Seria a fost comandată pentru a justifica efortul de război al Habsburgilor.'],
['portrete:10',    'cruciada',     'Campania cea Lungă a lui Iancu de Hunedoara, miniatură din Cronica lui Thuróczy, 1488. Expediția din 1443-1444 a dus armata creștină până în Balcani.'],
['portrete:5',     'cruciada',     'Diploma de înnobilare a lui Iancu de Hunedoara, dată de Ladislau al V-lea în februarie 1453. Actul consfințește ascensiunea unei familii de cnezi români în vârful nobilimii maghiare.'],
['portrete:71',    'cruciada',     'Blazonul acordat familiei Hunyadi prin diploma din 1453, cu corbul care avea să dea numele dinastiei Corvinilor.'],
['portrete:25',    'brancoveanu',  'Monedă de aur de zece ducați a principelui Gabriel Bethlen, Transilvania, 1616. Emisiunile mari de aur erau instrumente de prestigiu și de plată a mercenarilor.'],
['portrete:26',    'brancoveanu',  'Monedă de aur de douăzeci și cinci de ducați a principelui Mihail Apafi, 1681. Principatul își bate propria monedă și sub suzeranitate otomană.'],
['portrete:64',    'otoman',       'Monedă de necesitate bătută de Gabriel Báthory în timpul asediului Sibiului, 1611: metalul de la fața locului, tăiat în grabă, ca plată pentru trupe.'],
['portrete:77',    'otoman',       'Moneda lui Gabriel Báthory, 1609.'],
['portrete:73',    'brancoveanu',  'Mihail Apafi, principe al Transilvaniei, c. 1670. Ultimul principe autonom înainte de trecerea sub stăpânirea habsburgică.'],
['portrete:24',    'brancoveanu',  'Dimitrie Cantemir, portret din Descriptio Moldaviae, 1716. Domn pentru câteva luni, apoi exilat în Rusia, a devenit primul membru român al Academiei din Berlin.'],
['portrete:21',    'brancoveanu',  'Dimitrie Cantemir în gravura olandeză din 1735. Reputația lui europeană s-a construit pe scrierile de istorie otomană, nu pe scurta lui domnie.'],
['portrete:27',    'brancoveanu',  'Pagina de titlu a lucrării The History of the Growth and Decay of the Othman Empire, Londra, 1734-1735. Tradusă din latină, cartea lui Cantemir a fost timp de un secol lucrarea de referință a europenilor despre Imperiul Otoman.'],
['portrete:68',    'brancoveanu',  'Hronicul vechimei a romano-moldo-vlahilor, scris de Cantemir între 1717 și 1723: prima încercare sistematică de a demonstra originea latină și unitatea românilor.'],
['portrete:52',    'fanarioti',    'Reveria principelui Dimitrie Cantemir, gravură din 1788. Figura domnului-savant a intrat în imaginarul iluminist european.'],
['portrete:51',    'brancoveanu',  'Stema lui Constantin Brâncoveanu, 1700. Domnia lui de douăzeci și șase de ani a fost cea mai lungă din istoria Țării Românești.'],
['portrete:72',    'fanarioti',    'Asediul și cucerirea Iașilor, 1788, gravură contemporană. Războiul austro-ruso-turc a purtat frontul prin mijlocul Moldovei.'],
['portrete:0',     'otoman',       'Ocupația otomană a părții centrale a regatului maghiar, hartă din 1629: Transilvania rămâne principat autonom între două imperii.'],
['portrete:30',    'renastere',    'Alexandru Ioan Cuza, fotografie de Carol Popp de Szathmary. Szathmary a fost unul dintre cei dintâi fotografi de război din lume.'],
['portrete:66',    'renastere',    'Alexandru Ioan Cuza înainte de 1866.'],
['portrete:61',    'renastere',    'Deschiderea Adunării legiuitoare de către Cuza, 29 februarie 1860.'],
['portrete:55',    'renastere',    'Cuza și doctorul Carol Davila vizitează mahalaua Tabaci, inundată în 1862. Davila a întemeiat învățământul medical românesc.'],
['portrete:34',    'regat',        'Jurământul lui Carol I, 1866. Principele de Hohenzollern-Sigmaringen a ajuns în țară călătorind sub nume fals, pe Dunăre.'],
['portrete:70',    'regat',        'Carol I înmânează drapelele Gărzii Civice, 11 septembrie 1867.'],
['portrete:29',    'regat',        'Carol I la Slănic Moldova, 1891.'],
['portrete:19',    'mare-razboi',  'Funeraliile lui Carol I, 1914. Regele a murit la două luni după izbucnirea războiului, după ce Consiliul de Coroană îi respinsese cererea de a intra alături de Puterile Centrale.'],
['portrete:23',    'interbelic',   'Marioara și Carol al II-lea, fotografie de la începutul secolului al XX-lea.'],
['portrete:63',    'regat',        'Membrii Junimii, 1883. Societatea ieșenilor a dat țara doi prim-miniștri, o teorie critică influentă și cea mai importantă revistă literară a epocii.'],
['portrete:54',    'regat',        'Ex-librisul lui Ion Creangă, 1878.'],
['portrete:6',     'renastere',    'Sașa Cuza, c. 1889. Unul dintre cei doi fii pe care Alexandru Ioan Cuza i-a avut cu Maria Obrenovici și pe care Elena Cuza i-a crescut ca pe ai ei, după abdicare, în exilul de la Heidelberg.'],

/* ------------------------------- tiparituri ------------------------------ */
['tiparituri:7',   'brancoveanu',  'Filă din Codicele de la Ieud, c. 1630, unul dintre cele mai vechi manuscrise românești păstrate, scris cu litere chirilice.'],
['tiparituri:19',  'brancoveanu',  'Altă filă din Codicele de la Ieud. Textele religioase în limba română încep să circule în secolul al XVII-lea, înlocuind treptat slavona.'],
['tiparituri:12',  'brancoveanu',  'Pagină din Codicele de la Ieud, cu inițiale ornate în tradiția manuscriselor slavone.'],
['tiparituri:0',   'religie',      'Pomelnicul lui Nicolae Iovepali și al familiei sale de la schitul Cuvioasa Parascheva, c. 1800: lista morților pomeniți la slujbă, principalul document de istorie a familiilor târzii.'],
['tiparituri:1',   'religie',      'Îngroparea lui Avel, tipătură chirilică din 1818.'],
['tiparituri:3',   'limba',        'Alfabetul chirilic românesc în forma lui târzie, după Vasile Alecsandri, 1863. Trecerea oficială la litere latine se face între 1860 și 1862.'],
['tiparituri:5',   'renastere',    'Antet al Eforiei Spitalelor Civile din Principatele Unite, 1859, cu grafie chirilică și titulatura noului stat.'],
['tiparituri:6',   'renastere',    'Mozaicul, revistă apărută la Craiova la 3 octombrie 1838. Presa în limba română se înmulțește rapid după Regulamentele Organice.'],
['tiparituri:2',   'orase',        'Stema Iașilor, 1834.'],

/* --------------------------------- sec19 --------------------------------- */
['sec19:43',       'regat',        'Trecerea Dunării la Corabia, de Nicolae Grigorescu, 1877. Pictorul a însoțit armata ca martor oficial al campaniei.'],
['sec19:42',       'regat',        'Podul militar de vase peste Dunăre, de la Siliștioara la Măgura, 1877.'],
['sec19:19',       'regat',        'Atacul de la Smârdan, de Nicolae Grigorescu. Tabloul a devenit imaginea canonică a Războiului de Independență.'],
['sec19:1',        'regat',        'Redutele Griviței, 1881. Asaltul din 30 august 1877 a costat armata română peste o mie de morți într-o singură zi.'],
['sec19:33',       'regat',        'La Plevna, de Theodor Aman. Asediul a durat cinci luni și a decis soarta războiului.'],
['sec19:23',       'regat',        'Spionul, de Nicolae Grigorescu. Din campania din 1877 pictorul a adus mai puține scene de bătălie și mai multe figuri de oameni.'],
['sec19:21',       'regat',        'Roșiorul, de Nicolae Grigorescu.'],
['sec19:24',       'regat',        'Convoi de prizonieri, de Nicolae Grigorescu.'],
['sec19:26',       'regat',        'Parada la Nicopole, de Nicolae Grigorescu.'],
['sec19:3',        'regat',        'Pomenirea eroilor pe câmpiile Bulgariei, de Nicolae Grigorescu.'],
['sec19:0',        'regat',        'Armata rusă la București, The Illustrated London News, octombrie 1877. Trecerea trupelor țariste prin țară a precedat intrarea României în război.'],
['sec19:34',       'regat',        'Sosirea la București a marelui duce Nicolae, comandantul armatei ruse, 1877.'],
['sec19:5',        'regat',        'Explozia monitorului otoman Lutfi Djelil la Brăila, 1877. Scufundarea navei a deschis Dunărea pentru trupele aliate.'],
['sec19:11',       'regat',        'Monumentul comemorativ de la Rahova, 1902.'],
['sec19:16',       'regat',        'Actul proclamării Regatului României, 1881.'],
['sec19:17',       'regat',        'Încoronarea lui Carol I ca rege, 1881. Coroana a fost turnată din oțelul unui tun otoman capturat la Plevna.'],
['sec19:25',       'regat',        'Regele Carol I cu suita, fotografie de Carol Popp de Szathmary, 1881.'],
['sec19:14',       'atlas',        'România la 1887, hartă a Regatului după dobândirea Dobrogei.'],
['sec19:15',       'minoritati',   'Harta etnică a Austro-Ungariei și a României, 1892. Cartografia etnică devine, în ultimele decenii ale secolului al XIX-lea, un instrument al revendicărilor naționale.'],
['sec19:12',       'mare-razboi',  'România Mare, hartă publicată de The New York Times la 10 august 1919, în timpul Conferinței de Pace.'],
['sec19:13',       'regat',        'Calea ferată Lemberg-Cernăuți-Iași-Buzău-Mărășești, planșă din 1881. Rețeaua feroviară a legat Principatele de piețele europene și a schimbat geografia economică a țării.'],
['sec19:32',       'orase',        'Biserica lui Bucur, 1882. Tradiția o leagă de legenda întemeierii Bucureștiului, fără temei documentar.'],

/* ----------------------------- orase si viata ---------------------------- */
['orase-vechi:27', 'romi',         'Anunț de vânzare a două sute de familii de țigani, 1845. Robia romilor a fost desființată abia în 1855 în Moldova și în 1856 în Țara Românească, iar foștii robi nu au fost împroprietăriți.'],
['orase-vechi:18', 'orase',        'Bucureștiul, capitala Valahiei, gravură publicată la 13 septembrie 1856.'],
['orase-vechi:30', 'orase',        'Tramvaiul cu cai din București, 1871.'],
['orase-vechi:33', 'orase',        'Gara de Nord din București înainte de 1900.'],
['orase-vechi:14', 'orase',        'Piața Sfatului din Brașov, 1848. Orașele săsești au păstrat cel mai bine structura medievală: piața centrală, casa sfatului, ziduri de breaslă.'],
['orase-vechi:16', 'orase',        'Clujul în Civitates orbis terrarum al lui Braun și Hogenberg, 1617.'],
['orase-vechi:21', 'orase',        'Clujul după Jan Peeters, 1685.'],
['orase-vechi:24', 'orase',        'Clujul în desenul lui Conrad von Weiss, 1735.'],
['orase-vechi:19', 'orase',        'Panorama Clujului, c. 1840.'],
['orase-vechi:6',  'orase',        'Timișoara în jurul anului 1720, la scurt timp după cucerirea austriacă a Banatului.'],
['orase-vechi:5',  'orase',        'Planul cetății Timișoara, 1775.'],
['orase-vechi:32', 'orase',        'Strada Titu Maiorescu din Timișoara, înainte de 1899.'],
['orase-vechi:31', 'orase',        'Biserica Milenară din Timișoara, ridicată între 1896 și 1899.'],
['orase-vechi:28', 'orase',        'Târg în Transilvania, acuarelă de Lanzedelli, 1818.'],
['orase-vechi:29', 'renastere',    'Alexandru Lăpușneanul de Costache Negruzzi, în ediția din 1840, cu litere chirilice. Nuvela a fixat în literatura română imaginea domnului tiran.'],
['orase-vechi:26', 'cultura',      'Prima pagină a revistei Convorbiri Literare, 1 mai 1885. În paginile ei au apărut Eminescu, Creangă, Caragiale și Slavici.'],
['orase-vechi:40', 'mare-razboi',  'Constanța în septembrie 1916, după ocuparea orașului de trupele Puterilor Centrale.'],
['orase-vechi:38', 'interbelic',   'Palat bucureștean, fotografie din 1923. Contrastul dintre capitala și satul românesc a fost tema centrală a dezbaterii interbelice.'],
['orase-vechi:39', 'minoritati',   'Copii țărani în cămașă albă și iie cusută, fotografie din reportajul National Geographic despre România, 1923. Costumul de sărbătoare era țesut și cusut în gospodărie, iar motivele se citeau ca un act de identitate: sat, vârstă, stare civilă.'],
['orase-vechi:37', 'orase',        'Birjar bucureștean, 1923.'],

/* --------------------------------- sec20 --------------------------------- */
['sec20:16',       'mare-razboi',  'Fotografie de pe frontul românesc, 1916-1917, din albumul dăruit de generalul Rudianu. Campania din 1916 s-a încheiat cu pierderea a trei sferturi din teritoriu.'],
['sec20:18',       'mare-razboi',  'Trupe române pe front, 1916.'],
['sec20:14',       'mare-razboi',  'Inspectarea unui obuz neexplodat căzut în tranșeele românești, 6 mai 1916.'],
['sec20:27',       'mare-razboi',  'Gara Predeal distrusă de bombardamentul Puterilor Centrale, 1916.'],
['sec20:25',       'mare-razboi',  'Rețele de sârmă ghimpată pe frontul din Moldova, iarna 1917. După retragerea la Iași, frontul s-a stabilizat pe linia Siretului.'],
['sec20:41',       'mare-razboi',  'Bucureștiul bombardat din zeppelin, 1916.'],
['sec20:39',       'mare-razboi',  'Efectele bombardamentelor aeriene asupra Bucureștiului, 1916.'],
['sec20:6',        'mare-razboi',  'Sediul guvernământului imperial al Bucureștiului, 1916-1918, în timpul ocupației germane.'],
['sec20:40',       'mare-razboi',  'Generalul german Eberhard von Schmettow, comandant în România ocupată.'],
['sec20:47',       'mare-razboi',  'Demonstrație la București în favoarea intrării în război, 1915-1916. Țara a rămas neutră doi ani, sub presiunea celor două tabere.'],
['sec20:31',       'mare-razboi',  'Muncitoarele fabricii de paste din Galați protestează împotriva războiului, c. august 1916.'],
['sec20:35',       'mare-razboi',  'Regele Ferdinand depune jurământul.'],
['sec20:0',        'razboi2',      'Bistrița, strada Liviu Rebreanu, septembrie 1940: intrarea trupelor maghiare în nordul Transilvaniei cedat prin Dictatul de la Viena. Fotografie color de epocă.'],
['sec20:1',        'razboi2',      'Piața centrală a Clujului în ziua intrării trupelor maghiare, cu biserica Sfântul Mihail în fundal, septembrie 1940.'],
['sec20:3',        'razboi2',      'Năsăud, 1940: fotografie de grup la intrarea trupelor maghiare. Populația maghiară a primit schimbarea ca eliberare, cea românească drept catastrofă.'],
['sec20:8',        'razboi2',      'Nordul Transilvaniei, septembrie 1940.'],
['sec20:9',        'razboi2',      'Nordul Transilvaniei, septembrie 1940: săteni în costum popular așteptând pe marginea drumului.'],
['sec20:11',       'razboi2',      'Un steag cu inscripția Siebenbuergen unsere Heimat, purtat de comunitatea sasă la intrarea trupelor maghiare, 1940.'],
['sec20:13',       'razboi2',      'Nordul Transilvaniei, 1940.'],
['sec20:15',       'razboi2',      'Trupe maghiare intrând într-o localitate din nordul Transilvaniei, 1940.'],
['sec20:5',        'razboi2',      'Primirea armatei maghiare la Ilonda, 8 septembrie 1940.'],
['sec20:23',       'evrei',        'Publicație a Primăriei Pașcani, 4 iulie 1941: evreii găsiți pe stradă între orele 18 și 7 urmau să fie executați, primii dintre ei ostaticii aflați deja în arest. Documentul arată cum a funcționat administrativ persecuția.'],
['sec20:29',       'evrei',        'Grupuri de participanți la pogromul din București, ianuarie 1941. În timpul rebeliunii legionare au fost uciși o sută douăzeci și unu de evrei.'],
['sec20:26',       'evrei',        'La Podul Sabarului, ianuarie 1941: locul unde au fost duse și ucise o parte dintre victimele pogromului bucureștean.'],
['sec20:30',       'evrei',        'Cadavru neidentificat scos din canalul colector al Abatorului, ianuarie 1941. La abatorul din București au fost uciși evrei în timpul rebeliunii legionare.'],
['sec20:42',       'evrei',        'Templul Spaniol din București, ianuarie 1941, după devastarea din timpul rebeliunii legionare.'],
['sec20:49',       'evrei',        'București, 21-23 ianuarie 1941: rebeliunea legionară, înăbușită de armată la ordinul lui Antonescu.'],
['sec20:21',       'evrei',        'Proviziile lui Radu Lecca, împuternicitul guvernului pentru problemele evreiești, plătite de Centrala Evreilor, 1943. Instituția impusă comunității a fost folosită și pentru a-i extrage bani.'],
['sec20:37',       'evrei',        'Ședință literară la Baraseum, 1943. Teatrul evreiesc din București a funcționat în anii interzicerii evreilor din viața publică.'],
['sec20:22',       'razboi2',      'Act de identitate pentru refugiat polonez, eliberat la București în 1943. Prin România au trecut zeci de mii de refugiați polonezi după septembrie 1939.'],
['sec20:44',       'evrei',        'Selecția copiilor înaintea eliberării lor din Transnistria, 1944. Repatrierea orfanilor a început după ce guvernul Antonescu a schimbat cursul politicii sale.'],
['sec20:45',       'razboi2',      'Odesa în 1942, sub administrație românească. Orașul a fost capitala Transnistriei între 1941 și 1944.'],
['sec20:46',       'razboi2',      'Opera din Odesa în 1942.'],
['sec20:50',       'razboi2',      'Intrarea trupelor române întoarse de la Odesa pe Calea Victoriei, 8 noiembrie 1941.'],
['sec20:48',       'razboi2',      'Operațiunea Iași-Chișinău, august 1944: ofensiva sovietică ce a dus la prăbușirea frontului și la actul de la 23 august.'],
['sec20:34',       'romi',         'Țara Noastră, ediție specială săptămânală pentru romii din România, 1 august 1937. Presa romilor apare în anii 1930, odată cu Uniunea Generală a Romilor.'],
['sec20:32',       'interbelic',   'Cuvântul Liber, 1935: presa Frontului Popular, într-un deceniu în care extrema dreaptă câștigă teren.'],
['sec20:36',       'interbelic',   'Caricatura care îi ia în râs pe A. C. Cuza și pe Ion I. C. Brătianu, februarie 1923. Anul Constituției este și anul în care antisemitismul universitar devine mișcare de masă.'],
['sec20:7',        'interbelic',   'Garda zdrențăroasă la proclamarea Lajtabánság, 4 octombrie 1921: revizionismul maghiar imediat postbelic.'],

/* ============================ plansa cartografica ======================== */
['harti:29',       'atlas',        'Ungaria împărțită în trei, 1567: regatul habsburgic, pașalâcul de Buda și principatul Transilvaniei, configurația care a făcut posibilă autonomia transilvăneană.'],
['harti:71',       'atlas',        'Transilvania la 1572.'],
['harti:84',       'atlas',        'Transilvania în Cosmographia lui Sebastian Münster, una dintre cele dintâi reprezentări tipărite ale provinciei.'],
['harti:0',        'atlas',        'Romania, quae olim Thracia dicta, și regiunile vecine, Basel, 1584, colorată de mână.'],
['harti:15',       'atlas',        'Walachia, Servia, Bulgaria, Romania, de Gerard Mercator, 1589: prima hartă modernă dedicată special spațiului dintre Carpați și Balcani.'],
['harti:7',        'atlas',        'Walachia, Servia, Bulgaria, Romania, ediția din 1594 a hărții lui Mercator.'],
['harti:9',        'atlas',        'Daciarum Moesiarumque vetus descriptio, de Abraham Ortelius: geografia antică reconstituită după izvoarele scrise.'],
['harti:50',       'atlas',        'Transilvania, de Gerard Mercator, ediția din 1606.'],
['harti:55',       'atlas',        'Transilvania, de Abraham Ortelius, 1612.'],
['harti:30',       'atlas',        'Dacia și Moesia, de Abraham Ortelius, c. 1608.'],
['harti:13',       'atlas',        'Vetus descriptio Daciarum nec non Moesiarum, de Petrus Kaerius.'],
['harti:43',       'atlas',        'Transilvania, c. 1627.'],
['harti:48',       'atlas',        'Transilvania, după Mercator, ediție de la sfârșitul anilor 1620.'],
['harti:3',        'atlas',        'Walachia, Servia, Bulgaria, Romania, ediția din 1630.'],
['harti:12',       'atlas',        'Aceeași hartă în ediția din 1640, semn al longevității modelului mercatorian.'],
['harti:31',       'atlas',        'Valahia într-o reprezentare din 1643.'],
['harti:77',       'atlas',        'Walachia, Servia, Bulgaria, Romania, în atlasul lui Joan Blaeu, 1645.'],
['harti:36',       'atlas',        'Cursul Dunării, 1665.'],
['harti:64',       'atlas',        'Cartuș ornamental dintr-o hartă a Dunării de Nicolas Sanson, 1665.'],
['harti:54',       'atlas',        'La Transilvanie ou Sibenburgen, 1668.'],
['harti:19',       'atlas',        'Walachia, Seruia, Bulgaria, Romania, ediție de după 1673.'],
['harti:42',       'atlas',        'Principatul Transilvaniei împărțit în cinci națiuni, 1691. Împărțirea juridică în națiuni privilegiate a exclus populația românească majoritară.'],
['harti:20',       'atlas',        'Exactissima Tabula a cursului inferior al Dunării, c. 1700.'],
['harti:27',       'atlas',        'Transilvania și Moldova, de De La Feuille, 1710.'],
['harti:28',       'atlas',        'Imperiul Oriental și regiunile învecinate, de Banduri și Delisle, c. 1715, cu Moldova și Valahia ca entități distincte.'],
['harti:6',        'atlas',        'Ukrania quae et terra cosaccorum, cu Valahia și Moldova învecinate, de Johann Baptist Homann, 1724.'],
['harti:53',       'atlas',        'Tabula Valachiae Cisalutanae, 1722: Oltenia sub stăpânire austriacă, între 1718 și 1739.'],
['harti:74',       'atlas',        'Fragment heraldic din harta Valahiei Cisalutane, 1723.'],
['harti:68',       'atlas',        'Harta minieră a nordului Transilvaniei, din Danubius Pannonico-Mysicus, 1726. Aurul Apusenilor a fost motivul economic al tuturor stăpânirilor din regiune.'],
['harti:33',       'atlas',        'Turcia europeană, cu regiunile românești, de Herman Moll, 1726.'],
['harti:47',       'atlas',        'Principatul Transilvaniei împărțit în cinci națiuni, ediția din 1742.'],
['harti:4',        'atlas',        'Transylvaniae principatus in quinque nationes divisus, 1757, colorată de mână.'],
['harti:34',       'atlas',        'Tabula geographica continens Despotatus Wallachiae atque Moldaviae, 1769.'],
['harti:67',       'atlas',        'Ridicarea topografică iozefină a Banatului, 1769-1772: prima cartografiere sistematică, militară, a regiunii.'],
['harti:37',       'atlas',        'Siebenbürgen, hartă din 1789.'],
['harti:18',       'atlas',        'Ungaria și Transilvania, de Laurie și Whittle, 1794.'],
['harti:45',       'atlas',        'Harta generală a Valahiei, de Rigas Velestinlis, 1797. Cartograful grec, executat de otomani în 1798, o concepuse ca instrument al unei insurecții balcanice.'],
['harti:72',       'atlas',        'Harta României de Daniel Philippidis, 1816. Philippidis este cel care a impus în greacă numele de România pentru ansamblul celor două principate.'],
['harti:2',        'atlas',        'Schița militară a ținutului dintre Dunăre și Constantinopol, 1828, ridicată în timpul războiului ruso-turc.'],
['harti:21',       'atlas',        'Imperiul Austriac, de Pinkerton, 1818, colorată de mână.'],
['harti:63',       'atlas',        'Planul Bucureștiului întocmit de Vladimir de Blaremberg, 1842.'],
['harti:56',       'atlas',        'Dunărea de Jos, 1853.'],
['harti:52',       'atlas',        'Marele Principat al Transilvaniei după noua împărțire politică, 1854.'],
['harti:39',       'atlas',        'Principatele Dunărene, c. 1854, întocmite după harta de la Viena, în ajunul Războiului Crimeii.'],
['harti:24',       'atlas',        'Turcia europeană, Macedonia și Balcanii, de Colton, 1855.'],
['harti:46',       'atlas',        'Planul Bucureștiului ridicat de maiorul Dimitrie Pappasoglu, 1871.'],
['harti:51',       'atlas',        'Roumanie, 1886: Vechiul Regat la opt ani după recunoașterea independenței, cu Dobrogea adăugată și cu județele din sudul Basarabiei pierdute. Harta franceză arată și rețeaua de căi ferate abia terminată.'],
['harti:11',       'atlas',        'Valahia, gurile Dunării și vestul Transilvaniei, planșa din harta Scheda a Europei, c. 1860.'],
['harti:88',       'atlas',        'Harta generală a Imperiului Austriac, de Joseph von Scheda: cartografia militară austriacă a fost cea mai precisă a secolului al XIX-lea în regiune.'],
['harti:81',       'atlas',        'Sibiul în ridicarea topografică austriacă.'],
['harti:78',       'atlas',        'Segment din Tabula Peutingeriana cu Moesia Inferior de răsărit: copie medievală a unui itinerar rutier roman.'],
['harti:79',       'atlas',        'Segment din Tabula Peutingeriana cu Moesia Inferior de apus.'],
['harti:73',       'atlas',        'Harta Moldovei din Descriptio Moldaviae a lui Dimitrie Cantemir: prima hartă a țării întocmită de un român.'],
]
