export const meta = {
  name: 'istoria-romaniei-lot',
  description: 'Redacteaza si verifica un lot de capitole din istoria Romaniei',
  phases: [
    { title: 'Cercetare', detail: 'un istoric per epoca' },
    { title: 'Verificare', detail: 'fact-check adversarial' },
  ],
}

const CAP = [
  { id: 'preistorie', titlu: 'Zorii fierului si tracii nordici', per: 'c. 1000 - 514 i.Hr.', focus: 'Cultura Hallstatt si grupul Basarabi; trecerea de la bronz (Wietenberg, Monteoru, Noua) la fier; tracii nordici si diferentierea geto-dacilor de tracii sudici; metalurgia si depozitele de bronzuri; cetatile de pamant; coloniile grecesti de pe litoralul Marii Negre - Histria (c. 657 i.Hr.), Tomis, Callatis - si impactul lor comercial si cultural; primele mentiuni scrise; agatarsii lui Herodot; sciti in Dobrogea si Transilvania; tezaure (Hinova, Vaidei); societatea, religia si mestesugurile.' },
  { id: 'geti', titlu: 'Getii intre Darius si Alexandru', per: '514 - 300 i.Hr.', focus: 'Expeditia lui Darius I impotriva scitilor (514 i.Hr.) si getii "cei mai viteji si mai drepti dintre traci" la Herodot; religia - Zalmoxis, Gebeleizis, credinta in nemurire; campania lui Alexandru cel Mare la Dunare (335 i.Hr.); Zopyrion si dezastrul de la Olbia (331 i.Hr.); Dromichaites si captura lui Lisimah (c. 300-292 i.Hr.); organizarea socio-politica, tarabostes si comati; davae; economia, moneda greaca si imitatiile locale.' },
  { id: 'burebista', titlu: 'Regatul lui Burebista si Dacia preromana', per: '300 i.Hr. - 87 d.Hr.', focus: 'Celtii si bastarnii in spatiul carpato-danubian; monedele dacice de tip Husi-Vovriesti etc.; Burebista (c. 82-44 i.Hr.) si unificarea triburilor, rolul marelui preot Deceneu, distrugerea celtilor si a boilor lui Critasiros, campaniile la Olbia si Dionysopolis, decretul lui Acornion; relatia cu Pompei si planurile lui Caesar; destramarea regatului dupa 44 i.Hr.; Sarmizegetusa Regia si sistemul de cetati din Muntii Orastiei (Costesti, Blidaru, Piatra Rosie, Banita, Capalna); sanctuarele circulare si patrulatere, "soarele de andezit"; mestesugul fierului, ceramica, tezaurul si kosonii; expeditiile romane ale lui Cornelius Fuscus/Licinius Crassus la Dunare; Duras si Diurpaneus.' },
  { id: 'decebal', titlu: 'Decebal si razboaiele daco-romane', per: '87 - 106 d.Hr.', focus: 'Razboiul cu Domitian: Tapae (88), dezastrul lui Cornelius Fuscus (87), pacea "rusinoasa" din 89 si subsidiile; Decebal ca "rege client"; Traian si motivatiile campaniilor (aurul Daciei, securitatea Dunarii, prestigiul); podul lui Apollodor din Damasc la Drobeta; Primul razboi (101-102): Tapae, Adamclisi si campania moesica, pacea din 102; Al doilea razboi (105-106): asediul Sarmizegetusei, tradarea lui Bicilis, sinuciderea lui Decebal, capul adus la Roma, tezaurul din Sargetia; Columna lui Traian si Tropaeum Traiani ca izvoare vizuale; sursele - Dio Cassius, fragmentul lui Traian "inde Berzobim, deinde Aizi".' },
  { id: 'dacia-romana', titlu: 'Dacia romana si romanizarea', per: '106 - 275 d.Hr.', focus: 'Organizarea provinciei: Dacia Traiana, impartirile lui Hadrian si Marcus Aurelius (Superior/Inferior/Porolissensis, apoi Apulensis/Malvensis/Porolissensis), Dacia nu a inclus Moldova, Maramuresul si Crisana de nord; colonizarea "ex toto orbe Romano"; orasele - Ulpia Traiana Sarmizegetusa, Apulum, Napoca, Potaissa, Porolissum, Drobeta, Romula, Tibiscum; legiunile XIII Gemina si V Macedonica; limes-ul si castrele; economia - aurul de la Rosia Montana si tablitele cerate, sarea, fierul; religia sincretica, Mithra, Cavalerii Danubieni; latina vulgara si mecanismul romanizarii; dacii liberi (costoboci, carpi); retragerea aureliana (271-275) si Dacia Ripensis/Mediterranea; Dobrogea romana (Scythia Minor) care ramane in Imperiu pana in secolul VII.' },
  { id: 'migratii', titlu: 'Migratiile si etnogeneza romanilor', per: '275 - 1000', focus: 'Valurile migratoare: goti (cultura Santana de Mures-Cerneahov), huni, gepizi, avari, slavi, bulgari, maghiari, pecenegi, uzi, cumani; podul lui Constantin cel Mare si reocuparea partiala (328); crestinarea in limba latina - vocabularul fundamental crestin de origine latina (biserica, cruce, crestin, Dumnezeu, preot, a boteza), martirii de la Niculitel, donariul de la Biertan, Sf. Ioan Casian, Dionisie Exiguul; asimilarea slavilor si stratul slav in lexic; formarea limbii romane si dialectele sud-dunarene (aroman, meglenoroman, istroroman); teoria continuitatii (Xenopol, Parvan, Giurescu) vs. teoria imigrationista (Roesler, Sulzer) - argumente lingvistice, arheologice, toponimice si tacerea izvoarelor; "romanii" in izvoare bizantine si occidentale - Blachernae, vlahii lui Kekaumenos, 980; culturile arheologice Ipotesti-Candesti, Dridu; obstea sateasca si "romaniile populare".' },
  { id: 'voievodate', titlu: 'Primele formatiuni statale si Transilvania medievala', per: '1000 - 1330', focus: 'Gesta Hungarorum si voievozii Gelu, Glad, Menumorut - statut de izvor tardiv si controversa; cucerirea maghiara a Transilvaniei (sec. XI-XIII) si organizarea voievodatului (Mercurius princeps Ultrasilvanus, 1111); comitatele, sasii colonizati (Andreanum 1224) si secuii, Universitas Saxonum; Marea invazie mongola din 1241 si consecintele; Diploma cavalerilor ioaniti (1247) - Litovoi, Seneslau, Ioan, Farcas si cnezatele/voievodatele oltene; Basarabestii si Bogdanestii; Tara Severinului si Banatul de Severin; ortodoxia sub presiune catolica, episcopia cumanilor (1227); Dobrogea si Tara Cavarnei; primele urme documentare ale "Vlachilor".' },
  { id: 'intemeiere', titlu: 'Intemeierea Tarii Romanesti si a Moldovei', per: '1330 - 1418', focus: 'Basarab I si batalia de la Posada (9-12 noiembrie 1330) impotriva lui Carol Robert de Anjou, descrisa in Chronicon Pictum; Nicolae Alexandru si infiintarea Mitropoliei Ungrovlahiei (1359) sub patriarhia de la Constantinopol; Vladislav Vlaicu; "descalecatul" Moldovei - Dragos, Bogdan I (1359) si desprinderea de Ungaria, Petru I Musat, Roman I "de la munte pana la mare"; Mircea cel Batran (1386-1418): Rovine (1394/95), Nicopole (1396), alianta cu Sigismund de Luxemburg, stapanirea Dobrogei si a Amlasului si Fagarasului, primele plati de tribut; institutiile - domnie, sfat domnesc, boierime, Biserica, dregatorii; economia si drumurile comerciale, privilegiile pentru brasoveni si lioveni.' },
  { id: 'cruciada', titlu: 'Secolul cruciadei tarzii: Iancu, Vlad, Stefan', per: '1418 - 1504', focus: 'Alexandru cel Bun si consolidarea Moldovei; Iancu de Hunedoara - "Cavalerul Alb", victoriile de la Ialomita (1442), Campania cea Lunga (1443-44), dezastrul de la Varna (1444) si Kosovo (1448), apararea Belgradului (1456) si clopotele de amiaza; Vlad Tepes (1448, 1456-62, 1476) - politica interna, atacul nocturn de la Targoviste (1462), campania Dunarii, "scrisorile germane" si nasterea legendei, raportul cu mitul Dracula; Stefan cel Mare (1457-1504) - Baia (1467), Vaslui/Podul Inalt (10 ianuarie 1475), Valea Alba/Razboieni (1476), pierderea Chiliei si Cetatii Albe (1484), Codrii Cosminului (1497), ctitoriile si "Athletha Christi"; Matia Corvin si Transilvania; rascoala de la Bobalna (1437) si Unio Trium Nationum (1438).' },
  { id: 'otoman', titlu: 'Sub semiluna: suzeranitate, principat, Mihai Viteazul', per: '1504 - 1601', focus: 'Bogdan al III-lea si inchinarea Moldovei; Radu cel Mare, Neagoe Basarab si "Invataturile catre fiul sau Theodosie", biserica episcopala de la Curtea de Arges; Petru Rares; rascoala lui Gheorghe Doja (1514) si Tripartitum-ul lui Werboczi; Mohacs (1526) si prabusirea Ungariei; nasterea Principatului autonom al Transilvaniei sub suzeranitate otomana (1541, dupa caderea Budei), Ioan Sigismund, dieta si cele trei natiuni privilegiate, Reforma - luteranism sasesc, calvinism maghiar, unitarianism, edictul de la Turda (1568) si statutul "tolerat" al ortodocsilor; Ioan Voda cel Cumplit (1574); regimul tributului, mucarerul, haraciul si exploatarea economica; Mihai Viteazul (1593-1601): rascoala antiotomana, Calugareni si Giurgiu (1595), Selimbar (1599), unirea celor trei tari sub o singura autoritate (mai-septembrie 1600), Miraslau, Guruslau, asasinarea de pe Campia Turzii (9 august 1601) si semnificatia simbolica ulterioara.' },
  { id: 'brancoveanu', titlu: 'Secolul XVII: cultura, Habsburgii si sfarsitul autonomiei', per: '1601 - 1711', focus: 'Radu Serban, Gabriel Bethlen si "epoca de aur" a Principatului Transilvaniei; Matei Basarab (1632-54) si Vasile Lupu (1634-53) - tipografii, Pravila de la Govora, Cartea romaneasca de invatatura (1646), Indreptarea legii (1652), Academia Vasiliana; Mitropolitul Varlaam si Cazania (1643), Dosoftei si Psaltirea in versuri (1673), Biblia de la Bucuresti (1688); cronicarii moldoveni - Grigore Ureche, Miron Costin ("De neamul moldovenilor"), Ion Neculce - si munteni - Stolnicul Constantin Cantacuzino; ideea originii latine; Serban Cantacuzino si asediul Vienei (1683); Constantin Brancoveanu (1688-1714) - stilul brancovenesc, Hurezi, Mogosoaia, diplomatia intre Imperii, martiriul de la Constantinopol (15 august 1714) si canonizarea; Transilvania trece la Habsburgi (Diploma leopoldina, 1691) dupa Karlowitz (1699); Unirea unei parti a ortodocsilor cu Roma (1697-1701) si nasterea Bisericii Greco-Catolice; Dimitrie Cantemir, "Descriptio Moldaviae", alianta cu Petru cel Mare si infrangerea de la Stanilesti (1711).' },
  { id: 'fanarioti', titlu: 'Epoca fanariota si presiunea imperiilor', per: '1711 - 1821', focus: 'Instaurarea domniilor fanariote (Moldova 1711, Tara Romaneasca 1716) - mecanismul licitarii tronului, mazilirea, fiscalitatea; reformele lui Constantin Mavrocordat: desfiintarea rumaniei/veciniei (1746 in Tara Romaneasca, 1749 in Moldova), reforma fiscala si administrativa; razboaiele ruso-austro-turce si spatiul romanesc ca teatru de operatiuni; pierderi teritoriale - Oltenia sub austrieci (1718-1739), rapirea Bucovinei de catre Austria (1775) si protestul lui Grigore al III-lea Ghica, anexarea Basarabiei de catre Rusia prin Pacea de la Bucuresti (1812); Tratatul de la Kuciuk-Kainargi (1774) si protectoratul rus; in Transilvania: Scoala Ardeleana (Samuil Micu, Gheorghe Sincai, Petru Maior, Ion Budai-Deleanu) si latinismul, Supplex Libellus Valachorum (1791), rascoala lui Horea, Closca si Crisan (1784), Edictul de toleranta (1781), militarizarea granitei; iluminismul si primele scoli in limba romana; miscarea lui Tudor Vladimirescu si Eteria (1821) - Adunarea norodului, proclamatia de la Pades, ruptura cu Alexandru Ipsilanti, asasinarea la Targoviste; sfarsitul regimului fanariot.' },
  { id: 'renastere', titlu: 'Renasterea nationala si Unirea Principatelor', per: '1821 - 1866', focus: 'Domniile pamantene (1822), Conventia de la Akkerman (1826) si Tratatul de la Adrianopol (1829) - libertatea comertului cu cereale si integrarea in piata europeana; Regulamentele Organice (1831/32) sub Pavel Kiseleff - prima "constitutie" moderna, dar si claca sporita; miscarea nationala, Ion Campineanu, "Fratia"; Revolutia de la 1848: Iasi (petitia), Islaz si Proclamatia (9/21 iunie), Guvernul provizoriu, tricolorul, interventia turco-rusa, Transilvania - Adunarea de la Blaj (3/15 mai, "Noi vrem sa ne unim cu Tara"), Avram Iancu si Legiunea Gemina, razboiul civil cu revolutia maghiara, Andrei Saguna si petitia de la Viena; consecintele si emigratia; Razboiul Crimeii (1853-56), Congresul de la Paris (1856) - sfarsitul protectoratului rus, garantia colectiva, retrocedarea sudului Basarabiei; Adunarile ad-hoc (1857) si Conventia de la Paris (1858); dubla alegere a lui Alexandru Ioan Cuza (5/17 ianuarie in Moldova, 24 ianuarie/5 februarie 1859 in Tara Romaneasca); reformele Cuza-Kogalniceanu: secularizarea averilor manastiresti (1863), reforma agrara si Legea rurala (1864), Codul civil si penal, invatamantul obligatoriu, Universitatile din Iasi (1860) si Bucuresti (1864), Statutul dezvoltator; "monstruoasa coalitie" si abdicarea fortata (11 februarie 1866); aducerea lui Carol de Hohenzollern-Sigmaringen si Constitutia din 1866.' },
  { id: 'regat', titlu: 'Independenta si Regatul Romaniei', per: '1866 - 1914', focus: 'Carol I - domnie lunga, stabilitate institutionala, rotativa guvernamentala (1895) intre liberali (I.C. Bratianu, D.A. Sturdza) si conservatori (Lascar Catargiu, P.P. Carp, Titu Maiorescu); Razboiul de Independenta (1877-78): conventia cu Rusia, proclamarea independentei (9/21 mai 1877), Plevna, Grivita, Rahova, Smardan, generalii Cernat si Cernat/Coanda, "Va rog sa treceti Dunarea"; Congresul de la Berlin (1878) - independenta recunoscuta conditionat de art. 44 (chestiunea evreiasca), schimbul Dobrogei contra sudului Basarabiei; proclamarea Regatului (1881); modernizarea - caile ferate, podul de la Cernavoda (Saligny, 1895), portul Constanta, industria petrolului si primul rafinat din lume (1857 Ploiesti), Banca Nationala (1880); Junimea si "formele fara fond", Eminescu, Caragiale, Creanga, Maiorescu, Slavici; problema taraneasca si Rascoala din 1907 - 11.000 de morti (cifra dezbatuta), reprimarea de catre Averescu; miscarea nationala din Transilvania - Memorandumul (1892), procesul de la Cluj, PNR, "activism" vs "pasivism", legile Apponyi (1907), maghiarizarea; Al Doilea Razboi Balcanic (1913) si Pacea de la Bucuresti - anexarea Cadrilaterului.' },
  { id: 'mare-razboi', titlu: 'Marele Razboi si Romania Mare', per: '1914 - 1920', focus: 'Consiliul de Coroana de la Sinaia (1914) si neutralitatea; moartea lui Carol I si urcarea lui Ferdinand; tratativele si Tratatul de alianta cu Antanta (4/17 august 1916); intrarea in razboi (14/27 august 1916) si campania din Transilvania; contraofensiva Falkenhayn-Mackensen, Turtucaia, trecatorile, batalia de pe Arges/Neajlov, caderea Bucurestiului (6 decembrie 1916); refugiul la Iasi, tifosul exantematic, misiunea Berthelot; 1917 - reforma promisa de rege, Marasti, Marasesti ("Pe aici nu se trece", Ecaterina Teodoroiu), Oituz; Revolutia rusa si iesirea Rusiei din razboi, Armistitiul de la Focsani, Pacea de la Buftea-Bucuresti (mai 1918), reintrarea in razboi (10 noiembrie 1918); Marea Unire: Sfatul Tarii si unirea Basarabiei (27 martie/9 aprilie 1918), Congresul general al Bucovinei (15/28 noiembrie 1918), Marea Adunare Nationala de la Alba Iulia (1 decembrie 1918) - 1228 delegati, rezolutia lui Vasile Goldis, Consiliul Dirigent, Iuliu Maniu; campania din Ungaria si ocuparea Budapestei (1919); Conferinta de Pace de la Paris - Ion I.C. Bratianu si retragerea, Tratatul de la Saint-Germain, Trianon (4 iunie 1920), Neuilly, Paris (28 octombrie 1920 - Basarabia); Romania Mare: 295.000 kmp, ~16 milioane locuitori, ~28% minoritati.' },
  { id: 'interbelic', titlu: 'Romania interbelica: democratie, criza, autoritarism', per: '1920 - 1939', focus: 'Reforma agrara (1921) - una dintre cele mai radicale din Europa, ~6 milioane ha expropriate; votul universal masculin (1918/1923); Constitutia din 1923 si statul "national unitar"; PNL al Bratienilor si "prin noi insine" vs PNT (1926, fuziunea PNR-PT) si "portile deschise"; Regele Ferdinand, Actul de la 4 ianuarie 1926 si renuntarea lui Carol, Regenta, moartea lui Ferdinand (1927), revenirea lui Carol al II-lea (1930); criza economica 1929-33 si greva de la Grivita (1933); asasinatele politice - I.G. Duca (1933), Armand Calinescu (1939), Nicolae Iorga (1940); Legiunea Arhanghelul Mihail / Garda de Fier (Corneliu Zelea Codreanu, 1927) si extrema dreapta, antisemitismul, A.C. Cuza, Octavian Goga; instaurarea dictaturii regale (10 februarie 1938), Constitutia din 1938, FRN; economia - petrolul, IAR Brasov, Malaxa, Resita; cultura interbelica: George Enescu, Constantin Brancusi, Lucian Blaga, Mircea Eliade, Emil Cioran, Eugen Ionescu, Mihail Sebastian, Camil Petrescu, Liviu Rebreanu, Hortensia Papadat-Bengescu, Nicolae Titulescu si diplomatia (Mica Intelegere, Intelegerea Balcanica, Societatea Natiunilor), Henri Coanda, Gogu Constantinescu, Nicolae Paulescu si insulina, Emil Racovita, Traian Vuia, Aurel Vlaicu.' },
  { id: 'razboi2', titlu: 'Anul catastrofal 1940, Antonescu si Holocaustul', per: '1939 - 1944', focus: 'Pactul Ribbentrop-Molotov (23 august 1939) si protocolul secret; garantia franco-britanica si prabusirea Frantei; ultimatumurile sovietice (26-28 iunie 1940) si cedarea Basarabiei, nordului Bucovinei si tinutului Herta - 50.000 kmp; Dictatul de la Viena (30 august 1940) - nord-vestul Transilvaniei, 43.000 kmp, catre Ungaria; Tratatul de la Craiova (7 septembrie 1940) - Cadrilaterul catre Bulgaria; pierderi totale ~99.000 kmp si ~6,8 milioane locuitori; abdicarea lui Carol al II-lea (6 septembrie 1940), Mihai I si Ion Antonescu "Conducator"; Statul National Legionar, asasinatele de la Jilava, Snagov, rebeliunea legionara si pogromul de la Bucuresti (21-23 ianuarie 1941); aderarea la Pactul Tripartit (23 noiembrie 1940); Operatiunea Munchen si Barbarossa (22 iunie 1941), recucerirea Basarabiei si Bucovinei, decizia de a trece Nistrul, Odesa, Transnistria; Holocaustul din Romania: pogromul de la Iasi (iunie 1941, trenurile mortii, ~13.000 victime), deportarile in Transnistria, uciderea evreilor din Basarabia si Bucovina, masacrul de la Odesa (octombrie 1941), soarta romilor deportati, Comisia Internationala Wiesel si cifra de 280.000-380.000 de evrei ucisi in teritoriile administrate de Romania, plus ~135.000 din nordul Transilvaniei sub administratie maghiara la Auschwitz; supravietuirea unei parti a evreimii din Vechiul Regat; Stalingrad si dezastrul Armatelor 3 si 4 la Cotul Donului; bombardamentele asupra Ploiestiului (Operation Tidal Wave, 1 august 1943); Iasi-Chisinau si actul de la 23 august 1944 - arestarea lui Antonescu, intoarcerea armelor, ocuparea tarii de Armata Rosie, capturarea a ~130.000 de militari romani; campania din Ungaria si Cehoslovacia, ~170.000 de pierderi.' },
  { id: 'comunism1', titlu: 'Sovietizarea si stalinismul romanesc', per: '1944 - 1965', focus: 'Conventia de armistitiu (12 septembrie 1944) si Comisia Aliata de Control; "acordul de procentaje" Churchill-Stalin (octombrie 1944); guvernele Sanatescu si Radescu, manifestatia din 24 februarie 1945, ultimatumul lui Vasinski si guvernul Petru Groza (6 martie 1945); "greva regala"; alegerile falsificate din 19 noiembrie 1946; desfiintarea PNT dupa inscenarea de la Tamadau (1947), procesul si moartea lui Iuliu Maniu la Sighet; Tratatul de Pace de la Paris (10 februarie 1947) - recuperarea nordului Transilvaniei, confirmarea pierderii Basarabiei si Cadrilaterului, despagubiri; abdicarea fortata a Regelui Mihai (30 decembrie 1947) si proclamarea Republicii Populare; nationalizarea (11 iunie 1948), reforma invatamantului, desfiintarea Bisericii Greco-Catolice (1948); Securitatea (30 august 1948), Gulagul romanesc - Sighet, Aiud, Gherla, Ramnicu Sarat, Canalul Dunare-Marea Neagra, Periprava, coloniile de munca, "reeducarea" de la Pitesti; colectivizarea (1949-1962) si rezistenta taraneasca, rezistenta armata din munti (Arsenescu-Arnautoiu, Ogoranu, fratii Susman); Gheorghe Gheorghiu-Dej si eliminarea "moscovitilor" (Ana Pauker, Vasile Luca, Teohari Georgescu, 1952), procesul si executia lui Lucretiu Patrascanu (1954); Sovromurile si jaful economic; revolutia maghiara din 1956 si represiunea studenteasca; retragerea trupelor sovietice (1958); "Declaratia din aprilie" 1964 si inceputul distantarii de Moscova; amnistia detinutilor politici (1962-64).' },
  { id: 'ceausescu', titlu: 'Epoca Ceausescu', per: '1965 - 1989', focus: 'Nicolae Ceausescu succede lui Dej (martie 1965), Constitutia din 1965 si Republica Socialista Romania; "mica liberalizare" 1965-1971, desfiintarea cenzurii formale, deschiderea culturala; discursul din 21 august 1968 impotriva invadarii Cehoslovaciei si capitalul de imagine externa; vizitele lui de Gaulle (1968) si Nixon (1969), clauza natiunii celei mai favorizate, relatiile cu Israel si China; "Tezele din iulie" 1971 dupa vizita in Coreea de Nord si China - revolutia culturala romaneasca, Cantarea Romaniei; cultul personalitatii, "Conducator", "Geniul Carpatilor", elena Ceausescu si "savanta de renume mondial"; Decretul 770 (1966) - interzicerea avortului, cresterea natalitatii, mortalitatea materna, generatia "decreteilor", orfelinatele; Securitatea, informatorii, dosarele, Radio Europa Libera (Monica Lovinescu, Virgil Ierunca, Noel Bernard); cutremurul din 4 martie 1977 (1.578 de morti) si greva minerilor din Valea Jiului (august 1977); industrializarea fortata, Combinatul de la Galati, Canalul Dunare-Marea Neagra (1984), Casa Poporului si demolarea Uranusului, sistematizarea satelor; plata anticipata a datoriei externe (achitata in aprilie 1989) cu pretul exporturilor de alimente, rationalizarea, frigul, intreruperile de curent, cozile; Goma si miscarea pentru drepturile omului, Doina Cornea, scrisoarea celor sase (martie 1989); revolta de la Brasov (15 noiembrie 1987); politica externa - Helsinki, medierea Egipt-Israel; declinul final si izolarea dupa 1985 (Gorbaciov, perestroika respinsa).' },
  { id: 'revolutia', titlu: 'Revolutia din 1989', per: 'decembrie 1989', focus: 'Contextul: caderea regimurilor din Polonia, Ungaria, RDG, Cehoslovacia, Bulgaria; Congresul al XIV-lea al PCR (noiembrie 1989); Timisoara - solidaritatea in jurul pastorului Laszlo Tokes (15-16 decembrie), represiunea, mortii, "Timisoara - primul oras liber"; mitingul din 21 decembrie in Bucuresti si intreruperea transmisiunii, baricada de la Intercontinental; 22 decembrie - moartea lui Vasile Milea, fuga cu elicopterul de pe acoperisul CC, ocuparea Televiziunii, aparitia Frontului Salvarii Nationale; "teroristii" si haosul - majoritatea celor 1.104 morti si peste 3.000 de raniti au cazut dupa fuga lui Ceausescu; procesul sumar de la Targoviste si executia sotilor Ceausescu (25 decembrie 1989); dezbaterea istoriografica: revolutie, revolta populara confiscata sau lovitura de stat; dosarul Revolutiei si procesele tarzii; primele masuri ale FSN, comunicatul din 22 decembrie, abolirea pedepsei cu moartea, abrogarea decretului 770.' },
  { id: 'tranzitie', titlu: 'Tranzitia: de la FSN la NATO si UE', per: '1990 - 2007', focus: 'FSN se transforma in partid si castiga alegerile din 20 mai 1990 (Ion Iliescu 85%); Piata Universitatii, "Golaniada" si mineriada din 13-15 iunie 1990 - conditiile, victimele, condamnarea internationala; Constitutia din 1991; mineriada din septembrie 1991 si caderea guvernului Petre Roman; hiperinflatie, socul terapiei economice amanate, cupoanele si FPP, privatizarea, Bancorex si Banca Agricola; alegerile din 1996 si prima alternanta - Emil Constantinescu si CDR, reformele intarziate, inchiderea minelor si mineriada din 1999; retrocedari, restituirea proprietatilor, legea 18/1991 si legea 10/2001; revenirea PSD si Adrian Nastase (2000-2004), aderarea la NATO (29 martie 2004), incheierea negocierilor cu UE; Traian Basescu (2004), "alianta DA", suspendarile din 2007 si 2012; aderarea la Uniunea Europeana (1 ianuarie 2007) si MCV; deschiderea Arhivelor Securitatii si CNSAS, Raportul Tismaneanu (2006) si condamnarea oficiala a comunismului; emigratia masiva dupa liberalizarea vizelor (2002) - milioane de romani in Italia, Spania, Germania, Marea Britanie; declinul demografic.' },
  { id: 'contemporan', titlu: 'Romania in Uniunea Europeana', per: '2007 - 2026', focus: 'Criza economica din 2008-2010, acordul cu FMI, taierea salariilor bugetare cu 25% si majorarea TVA la 24%; guvernele Boc, Ponta, suspendarea lui Basescu (2012); lupta anticoruptie - DNA sub Laura Codruta Kovesi, condamnarea unor ministri si a fostului premier Adrian Nastase, dosarele grele; protestele din 2013 (Rosia Montana), incendiul din clubul Colectiv (30 octombrie 2015, 65 de morti) si caderea guvernului Ponta, guvernul tehnocrat Ciolos; OUG 13 si protestele din februarie 2017 - cele mai mari de dupa 1989, "Diaspora acasa" si 10 august 2018; Klaus Iohannis presedinte (2014-2024), guvernele PSD si motiunile; pandemia COVID-19 si impactul; razboiul din Ucraina (2022) - refugiatii ucraineni, coridoarele de cereale prin Constanta, dronele cazute pe teritoriul romanesc, cheltuielile de aparare, rolul in flancul estic al NATO; aderarea partiala la Schengen (aerian si maritim, martie 2024) si completa (terestru, 1 ianuarie 2025); alegerile prezidentiale din noiembrie-decembrie 2024, anularea turului I de catre CCR pe motive de ingerinta si campanie ilegala pe TikTok, cazul Calin Georgescu, repetarea scrutinului in mai 2025 si victoria lui Nicusor Dan asupra lui George Simion; ascensiunea AUR si a suveranismului; economia - crestere puternica dar deficite mari, IT si industria auto (Dacia, Ford Craiova), fondurile PNRR; demografia - populatie de ~19 milioane la recensamantul din 2021 fata de 23,2 milioane in 1990, diaspora de ~4-5 milioane; starea actuala a tarii la 2026 (mentioneaza explicit ce e sigur si ce e in curs).' },
]

const TEME = [
  { id: 'limba', titlu: 'Limba romana', focus: 'Originea latina si structura lexicala (fondul latin mostenit, substratul traco-dac cu ~90-160 de cuvinte - brad, barza, mal, viezure, copil, mos -, superstratul slav, imprumuturile maghiare, turcesti, grecesti, apoi re-latinizarea si franceza in secolul XIX); dialectele - dacoroman, aroman, meglenoroman, istroroman; primele texte in romana - Scrisoarea lui Neacsu din Campulung (1521), Psaltirea Scheiana, tipariturile lui Coresi; alfabetul chirilic si trecerea la alfabetul latin (oficial 1860-1862); Academia Romana (1866) si normarea; conflictul latinist-etimologist; reforma ortografica din 1953 si revenirea la "a-circumflex" si "sunt" in 1993; statutul limbii in Republica Moldova si disputa "limba moldoveneasca"; numarul de vorbitori azi.' },
  { id: 'religie', titlu: 'Religie si Biserica', focus: 'Crestinarea timpurie in limba latina si absenta unui act de crestinare de stat; Scythia Minor si episcopatele Dunarii de Jos; slavonismul liturgic si trecerea la romana in secolul XVII; mitropoliile Ungrovlahiei (1359) si Moldovei (1401); relatia cu Patriarhia ecumenica si autocefalia (1885), Patriarhia Romana (1925); Biserica Greco-Catolica (1697-1701), rolul ei in Scoala Ardeleana si desfiintarea brutala din 1948, restaurarea dupa 1989 si litigiile privind lacasurile; protestantismul in Transilvania si edictul de la Turda (1568); comunitatile evreiesti si musulmane (tatarii si turcii din Dobrogea); Biserica sub comunism - compromis, colaborare si rezistenta, "Rugul Aprins", martirii; religiozitatea in Romania de azi - cifre de recensamant, Catedrala Nationala, dezbaterea despre secularizare si referendumul din 2018.' },
  { id: 'minoritati', titlu: 'Minoritatile', focus: 'Maghiarii si secuii - istorie, statistica, Regiunea Autonoma Maghiara (1952-1968), UDMR dupa 1989, conflictul de la Targu Mures (martie 1990), invatamantul in limba maghiara, chestiunea autonomiei Tinutului Secuiesc; sasii si svabii - colonizarea din secolul XII, Universitas Saxonum, deportarea in URSS (1945), "vanzarea" germanilor catre RFG in schimbul unor sume pe cap de om, exodul din 1990 si comunitatile ramase, cazul Klaus Iohannis; evreii - de la privilegiile medievale la art. 44 al Tratatului de la Berlin, la antisemitismul interbelic, Holocaust, emigrarea in Israel (inclusiv rascumpararea organizata) si comunitatea reziduala de azi; romii - robia in Tarile Romane pana la dezrobirea din 1855-56, deportarile in Transnistria, situatia socio-economica actuala, discriminarea, cifrele de recensamant contra estimarilor; alte comunitati - ucraineni, rusi-lipoveni, turci si tatari, sarbi, bulgari, armeni, greci, ceangai; cadrul legal actual (locurile rezervate in Parlament, Legea 215).' },
  { id: 'cultura', titlu: 'Cultura si stiinta', focus: 'De la manuscrisele slavone si stilul brancovenesc la arta moderna; literatura - Eminescu, Caragiale, Creanga, Slavici, Rebreanu, Sadoveanu, Arghezi, Barbu, Blaga, Bacovia, Sorescu, Nichita Stanescu, Marin Preda, Norman Manea, Mircea Cartarescu, Herta Muller si Nobelul din 2009, Ana Blandiana si literatura de rezistenta; artele plastice - Nicolae Grigorescu, Theodor Aman, Stefan Luchian, Constantin Brancusi si Ansamblul de la Targu Jiu, Victor Brauner, Daniel Spoerri; muzica - George Enescu, Dinu Lipatti, Clara Haskil, Sergiu Celibidache, Angela Gheorghiu, folclorul si Maria Tanase; teatru si film - Eugen Ionescu si teatrul absurdului, Liviu Ciulei, Lucian Pintilie, Noul Val Romanesc (Cristian Mungiu si Palme dOr 2007, Cristi Puiu, Corneliu Porumboiu, Radu Jude si Ursul de Aur 2021); stiinta - Nicolae Paulescu si pancreina, Gheorghe Marinescu, Victor Babes, Ana Aslan, Emil Racovita, Henri Coanda, Traian Vuia, Aurel Vlaicu, Hermann Oberth, Stefan Odobleja, George Emil Palade si Nobelul din 1974, Elie Wiesel si Nobelul pentru Pace 1986, Stefan Hell si Nobelul pentru Chimie 2014; matematica romaneasca si olimpiadele; exilul cultural - Eliade, Cioran, Ionesco si problema angajamentelor lor interbelice.' },
  { id: 'economie', titlu: 'Economia si societatea', focus: 'De la economia agrara si "a doua iobagie" la exportul de cereale dupa 1829; chestiunea agrara ca fir rosu - claca, reforma din 1864, 1921 si 1945, colectivizarea, decolectivizarea haotica de dupa 1991 si faramitarea proprietatii; petrolul - prima productie inregistrata statistic in lume (1857), Ploiestiul, capitalul strain, nationalizarea, declinul; industrializarea comunista si supra-dimensionarea, dezindustrializarea anilor 1990; datoria externa platita in 1989 si costul social; tranzitia - inflatie, somaj, privatizari controversate; economia de azi - PIB si convergenta cu media UE, IT&C si outsourcing, industria auto (Dacia-Renault, Ford), agricultura, fondurile europene si PNRR, deficitul bugetar si de cont curent, inegalitatile regionale intre Bucuresti-Ilfov si Nord-Est; demografia - scaderea de la 23,2 milioane (1990) la ~19 milioane (recensamant 2021), imbatranirea, emigratia de 4-5 milioane si remitentele, natalitatea, speranta de viata, exodul medicilor.' },
  { id: 'geografie', titlu: 'Pamantul si oamenii', focus: 'Cadrul geografic ca personaj al istoriei: arcul Carpatilor (Orientali, Meridionali/Alpii Transilvaniei, Occidentali) si rolul lor de refugiu si de bariera; Podisul Transilvaniei ca cetate naturala; Campia Romana si Campia de Vest ca drumuri de invazie; Dunarea - granita imperiala, artera comerciala, Comisia Europeana a Dunarii (1856), Portile de Fier; Delta Dunarii si statutul de rezervatie a biosferei UNESCO; Marea Neagra si Dobrogea ca punte intre lumi; podisul Moldovei si culoarul de stepa pe unde au venit migratorii; resursele - sare, aur (Rosia Montana si Muntii Apuseni), petrol, gaze (Marea Neagra), lemn si defrisarile ilegale; clima si marile catastrofe - seceta din 1946-47 si foametea, inundatiile, cutremurele Vrancei (1802, 1940, 1977) si riscul seismic al Bucurestiului; oras si sat - urbanizarea tarzie, Bucurestiul si transformarile lui, satul romanesc si depopularea; patrimoniul UNESCO - bisericile pictate din nordul Moldovei, bisericile de lemn din Maramures, satele cu biserici fortificate din Transilvania, cetatile dacice, Manastirea Horezu, Sighisoara, Delta.' },
]

const SCHEMA = {
  type: 'object',
  properties: {
    rezumat: { type: 'string', description: 'Un paragraf de 80-120 de cuvinte care rezuma epoca. Registru enciclopedic, in limba romana cu diacritice.' },
    sectiuni: {
      type: 'array',
      description: '4-7 subsectiuni tematice/narative care acopera epoca in profunzime',
      items: {
        type: 'object',
        properties: {
          subtitlu: { type: 'string' },
          paragrafe: { type: 'array', items: { type: 'string' }, description: '2-5 paragrafe de cate 90-180 de cuvinte fiecare' },
        },
        required: ['subtitlu', 'paragrafe'],
      },
    },
    cronologie: {
      type: 'array',
      description: '8-16 repere datate, in ordine cronologica',
      items: {
        type: 'object',
        properties: { an: { type: 'string' }, eveniment: { type: 'string', description: '15-35 de cuvinte' } },
        required: ['an', 'eveniment'],
      },
    },
    figuri: {
      type: 'array',
      description: '2-5 personaje sau institutii definitorii',
      items: {
        type: 'object',
        properties: { nume: { type: 'string' }, ani: { type: 'string' }, rol: { type: 'string' }, descriere: { type: 'string', description: '45-80 de cuvinte' } },
        required: ['nume', 'ani', 'rol', 'descriere'],
      },
    },
    cifre: {
      type: 'array',
      description: '2-4 cifre-cheie verificabile (suprafete, populatii, victime, durate)',
      items: {
        type: 'object',
        properties: { valoare: { type: 'string' }, eticheta: { type: 'string' }, nota: { type: 'string' } },
        required: ['valoare', 'eticheta', 'nota'],
      },
    },
    citat: {
      type: 'object',
      description: 'Un citat de epoca autentic, cu autor si context. Daca nu exista unul sigur, lasa textul gol.',
      properties: { text: { type: 'string' }, autor: { type: 'string' }, context: { type: 'string' } },
      required: ['text', 'autor', 'context'],
    },
    controversa: { type: 'string', description: '60-120 de cuvinte despre principala disputa istoriografica a epocii, prezentand corect ambele pozitii. Gol daca nu exista una notabila.' },
    ilustratie: { type: 'string', description: 'Descrierea unei singure ilustratii/harti/diagrame care ar servi cel mai bine acest capitol, cu elementele geografice sau vizuale concrete de reprezentat.' },
  },
  required: ['rezumat', 'sectiuni', 'cronologie', 'figuri', 'cifre', 'citat', 'controversa', 'ilustratie'],
}

const VERIF = {
  type: 'object',
  properties: {
    corectii: { type: 'array', items: { type: 'string' }, description: 'Lista erorilor gasite si corectate. Gol daca nu s-a gasit nimic.' },
    continut: SCHEMA,
  },
  required: ['corectii', 'continut'],
}

const REGISTRU = `Scrii pentru o enciclopedie de referinta in limba romana, la nivelul Encyclopaedia Britannica.
REGULI DE STIL, obligatorii:
- Limba romana literara, cu diacritice corecte (a-circumflex, a-breve, i-circumflex, s-virgula, t-virgula). Foloseste diacriticele peste tot.
- Registru academic, sobru, la persoana a treia. Fara adresare directa catre cititor, fara exclamatii, fara emoji, fara limbaj publicitar sau patriotard.
- Precizie: date exacte (zi/luna/an unde se stie), nume complete, cifre cu sursa implicita. Cand o cifra e disputata, spune-o ("estimarile variaza intre X si Y").
- Cand un fapt e incert sau legendar, marcheaza-l ca atare. Nu prezenta traditia istoriografica romantica drept fapt stabilit.
- Nu evita subiectele dificile: Holocaustul din Romania, colaborationismul, represiunea comunista, minoritatile, mineriadele, esecurile tranzitiei.
- Nu folosi formulari de tip lista-in-proza. Scrie proza narativa densa, cu tranzitii.
- Foloseste stilul indirect pentru izvoare: "potrivit lui Dio Cassius", "Chronicon Pictum relateaza".
Nu scrie titlul capitolului in text; el va fi adaugat separat.`


const cerute = Array.isArray(args) ? args : []
const loturi = []
for (const c of CAP) if (cerute.includes(c.id)) loturi.push({ ...c, tip: 'cap' })
for (const t of TEME) if (cerute.includes(t.id)) loturi.push({ ...t, per: 'transversal', tip: 'tema' })

phase('Cercetare')
log(`Lot de ${loturi.length}: ${loturi.map((x) => x.id).join(', ')}`)

const rezultate = await pipeline(
  loturi,
  (c) => agent(
    c.tip === 'tema'
      ? `${REGISTRU}\n\nRedacteaza sectiunea tematica transversala "${c.titlu}" pentru o istorie enciclopedica a Romaniei. Spre deosebire de capitolele cronologice, aceasta sectiune urmareste un singur fir prin toate epocile, de la antichitate pana in 2026.\n\nTEME OBLIGATORII:\n${c.focus}\n\nVolum tinta: 1000-1500 de cuvinte de proza in campul "sectiuni". Cronologia sa contina reperele specifice acestei teme, nu istoria politica generala.`
      : `${REGISTRU}\n\nRedacteaza capitolul enciclopedic "${c.titlu}" (${c.per}) din istoria Romaniei si a spatiului carpato-danubiano-pontic.\n\nTEME OBLIGATORII de acoperit (nu te limita la ele, dar nu omite nimic esential de aici):\n${c.focus}\n\nVolum tinta: 1400-2200 de cuvinte de proza in campul "sectiuni", plus cronologia, figurile si cifrele.`,
    { label: `${c.tip === 'tema' ? 'tema' : 'scrie'}:${c.id}`, phase: 'Cercetare', schema: SCHEMA, effort: 'high' }
  ),
  (draft, c) => {
    if (!draft) return null
    return agent(
      `${REGISTRU}\n\nEsti redactor-verificator la o enciclopedie. Mai jos e draftul sectiunii "${c.titlu}" (${c.per}) din istoria Romaniei.\n\nSARCINA:\n1. Verifica adversarial fiecare data, nume propriu, cifra si atributie de citat. Cauta erori concrete: ani gresiti, batalii atribuite gresit, cifre umflate, citate apocrife, anacronisme, confuzii intre persoane omonime.\n2. Verifica daca lipseste ceva esential din temele care trebuiau acoperite: ${c.focus}\n3. Verifica echilibrul: sa nu existe nici ton nationalist necritic, nici omisiuni ale paginilor dificile.\n4. Verifica diacriticele si corectitudinea limbii romane.\n5. Returneaza continutul INTEGRAL corectat si, unde e cazul, completat, respectand acelasi format si acelasi volum sau mai mare. Nu scurta textul.\n6. In campul "corectii" listeaza pe scurt ce ai schimbat si de ce.\n\nDRAFT:\n${JSON.stringify(draft)}`,
      { label: `verifica:${c.id}`, phase: 'Verificare', schema: VERIF, effort: 'high' }
    ).then((v) => (v ? { id: c.id, tip: c.tip, corectii: v.corectii, ...v.continut } : { id: c.id, tip: c.tip, corectii: [], ...draft }))
  }
)

return { lot: cerute, rezultate: rezultate.filter(Boolean) }
